CCTLD = {
        "AD": "Andorra",
        "AE": "United arab emirates",
        "AG": "Antigua and barbuda",
        "AI": "Anguilla",
        "AL": "Albania",
        "AM": "Armenia",
        "AO": "Angola",
        "AQ": "Antarctica",
        "AR": "Argentina",
        "AS": "American samoa",
        "AT": "Austria",
        "AU": "Australia",
        "AW": "Aruba",
        "AX": "Åland islands",
        "AZ": "Azerbaijan",
        "BA": "Bosnia and herzegovina",
        "BB": "Barbados",
        "BD": "Bangladesh",
        "BE": "Belgium",
        "BF": "Burkina faso",
        "BG": "Bulgaria",
        "BH": "Bahrain",
        "BI": "Burundi",
        "BJ": "Benin",
        "BL": "Saint barthélemy",
        "BM": "Bermuda",
        "BN": "Brunei darussalam",
        "BO": "Bolivia, plurinational state of",
        "BQ": "Bonaire, sint eustatius and saba",
        "BR": "Brazil",
        "BS": "Bahamas",
        "BT": "Bhutan",
        "BV": "Bouvet island",
        "BW": "Botswana",
        "BY": "Belarus",
        "BZ": "Belize",
        "CA": "Canada",
        "CC": "Cocos (keeling) islands",
        "CD": "Congo",
        "CF": "Central african republic",
        "CG": "Congo",
        "CH": "Switzerland",
        "CK": "Cook islands",
        "CL": "Chile",
        "CM": "Cameroon",
        "CN": "China",
        "CO": "Colombia",
        "CR": "Costa rica",
        "CU": "Cuba",
        "CV": "Cape verde",
        "CW": "Curaçao",
        "CX": "Christmas island",
        "CY": "Cyprus",
        "CZ": "Czech republic",
        "DE": "Germany",
        "DJ": "Djibouti",
        "DK": "Denmark",
        "DM": "Dominica",
        "DO": "Dominican republic",
        "DZ": "Algeria",
        "EC": "Ecuador",
        "EE": "Estonia",
        "EG": "Egypt",
        "EH": "Western sahara",
        "ER": "Eritrea",
        "ES": "Spain",
        "ET": "Ethiopia",
        "F	": "fghanistan",
        "FI": "Finland",
        "FJ": "Fiji",
        "FK": "Falkland islands (malvinas)",
        "FM": "Micronesia, federated states of",
        "FO": "Faroe islands",
        "FR": "France",
        "GA": "Gabon",
        "GB": "United kingdom",
        "GD": "Grenada",
        "GE": "Georgia",
        "GF": "French guiana",
        "GG": "Guernsey",
        "GH": "Ghana",
        "GI": "Gibraltar",
        "GL": "Greenland",
        "GM": "Gambia",
        "GN": "Guinea",
        "GP": "Guadeloupe",
        "GQ": "Equatorial guinea",
        "GR": "Greece",
        "GS": "South georgia and the south sandwich islands",
        "GT": "Guatemala",
        "GU": "Guam",
        "GW": "Guinea-bissau",
        "GY": "Guyana",
        "HK": "Hong kong",
        "HM": "Heard island and mcdonald islands",
        "HN": "Honduras",
        "HR": "Croatia",
        "HT": "Haiti",
        "HU": "Hungary",
        "ID": "Indonesia",
        "IE": "Ireland",
        "IL": "Israel",
        "IM": "Isle of man",
        "IN": "India",
        "IO": "British indian ocean territory",
        "IQ": "Iraq",
        "IR": "Iran, islamic republic of",
        "IS": "Iceland",
        "IT": "Italy",
        "JE": "Jersey",
        "JM": "Jamaica",
        "JO": "Jordan",
        "JP": "Japan",
        "KE": "Kenya",
        "KG": "Kyrgyzstan",
        "KH": "Cambodia",
        "KI": "Kiribati",
        "KM": "Comoros",
        "KN": "Saint kitts and nevis",
        "KR": "Korea, republic of",
        "KW": "Kuwait",
        "KY": "Cayman islands",
        "KZ": "Kazakhstan",
        "LB": "Lebanon",
        "LC": "Saint lucia",
        "LI": "Liechtenstein",
        "LK": "Sri lanka",
        "LR": "Liberia",
        "LS": "Lesotho",
        "LT": "Lithuania",
        "LU": "Luxembourg",
        "LV": "Latvia",
        "LY": "Libyan arab jamahiriya",
        "MA": "Morocco",
        "MC": "Monaco",
        "MD": "Moldova, republic of",
        "ME": "Montenegro",
        "MF": "Saint martin (french part)",
        "MG": "Madagascar",
        "MH": "Marshall islands",
        "MK": "Macedonia, the former yugoslav republic of",
        "ML": "Mali",
        "MM": "Myanmar",
        "MN": "Mongolia",
        "MO": "Macao",
        "MP": "Northern mariana islands",
        "MQ": "Martinique",
        "MR": "Mauritania",
        "MS": "Montserrat",
        "MT": "Malta",
        "MU": "Mauritius",
        "MV": "Maldives",
        "MW": "Malawi",
        "MX": "Mexico",
        "MY": "Malaysia",
        "MZ": "Mozambique",
        "NA": "Namibia",
        "NC": "New caledonia",
        "NE": "Niger",
        "NF": "Norfolk island",
        "NG": "Nigeria",
        "NI": "Nicaragua",
        "NL": "Netherlands",
        "NO": "Norway",
        "NP": "Nepal",
        "NR": "Nauru",
        "NU": "Niue",
        "NZ": "New zealand",
        "OM": "Oman",
        "PA": "Panama",
        "PE": "Peru",
        "PF": "French polynesia",
        "PG": "Papua new guinea",
        "PH": "Philippines",
        "PK": "Pakistan",
        "PL": "Poland",
        "PM": "Saint pierre and miquelon",
        "PN": "Pitcairn",
        "PR": "Puerto rico",
        "PS": "Palestinian territory, occupied",
        "PT": "Portugal",
        "PW": "Palau",
        "PY": "Paraguay",
        "QA": "Qatar",
        "RE": "Réunion",
        "RO": "Romania",
        "RS": "Serbia",
        "RU": "Russia",
        "RW": "Rwanda",
        "SA": "Saudi arabia",
        "SB": "Solomon islands",
        "SC": "Seychelles",
        "SD": "Sudan",
        "SE": "Sweden",
        "SG": "Singapore",
        "SH": "Saint helena, ascension and tristan da cunha",
        "SI": "Slovenia",
        "SJ": "Svalbard and jan mayen",
        "SK": "Slovakia",
        "SL": "Sierra leone",
        "SM": "San marino",
        "SN": "Senegal",
        "SO": "Somalia",
        "SR": "Suriname",
        "SS": "South sudan",
        "ST": "Sao tome and principe",
        "SV": "El salvador",
        "SX": "Sint maarten (dutch part)",
        "SY": "Syrian arab republic",
        "SZ": "Swaziland",
        "TC": "Turks and caicos islands",
        "TD": "Chad",
        "TF": "French southern territories",
        "TG": "Togo",
        "TH": "Thailand",
        "TJ": "Tajikistan",
        "TK": "Tokelau",
        "TL": "Timor-leste",
        "TM": "Turkmenistan",
        "TN": "Tunisia",
        "TO": "Tonga",
        "TR": "Turkey",
        "TT": "Trinidad and tobago",
        "TV": "Tuvalu",
        "TW": "Taiwan, province of china",
        "TZ": "Tanzania, united republic of",
        "UA": "Ukraine",
        "UG": "Uganda",
        "UK": "UK",
        "UM": "United states minor outlying islands",
        "US": "USA",
        "UY": "Uruguay",
        "UZ": "Uzbekistan",
        "VA": "Holy see (vatican city state)",
        "VC": "Saint vincent and the grenadines",
        "VE": "Venezuela, bolivarian republic of",
        "VG": "Virgin islands, british",
        "VI": "Virgin islands, u.s.",
        "VN": "Viet nam",
        "VU": "Vanuatu",
        "WF": "Wallis and futuna",
        "WS": "Samoa",
        "YE": "Yemen",
        "YT": "Mayotte",
        "ZA": "South africa",
        "ZM": "Zambia",
        "ZW": "Zimbabwe"
    }

COMPANY_COUNTRY = {
        "https://github.com/google": "USA",
        "Red Hat": "USA",
        "(Independent)": "free",
        "@10gen": "USA",
        "@adobe": "USA",
        "@airbnb": "USA",
        "@alfresco": "USA",
        "@Alfresco": "USA",
        "@alibaba": "China",
        "@alibaba cloud": "China",
        "@alipay": "China",
        "@amzn": "USA",
        "@apache": "USA",
        "@apple": "USA",
        "@apple @apache": "USA",
        "@arangodb": "USA",
        "@ARM-software": "UK",
        "@ARM-software @ARMmbed": "UK",
        "@ARMmbed": "UK",
        "@atlassian": "Sydney",
        "@auth0": "USA",
        "@aws": "USA",
        "@awslabs": "USA",
        "@Azure @Microsoft": "USA",
        "@BackMarket": "France",
        "@bbc": "UK",
        "@Bloomberg": "USA",
        "@brain-research @Google-Research": "USA",
        "@Bytedance": "China",
        "@camunda": "Germany",
        "@CanonicalLtd": "UK",
        "@Canva": "USA",
        "@CapitalOne": "USA",
        "@cerner": "USA",
        "@cloudera": "USA",
        "@Cloudera @apache": "USA",
        "@cloudflare": "USA",
        "@codecentric": "Germany",
        "@cohere-ai @VectorInstitute @Google": "USA",
        "@collabora": "UK",
        "@Comcast": "USA",
        "@confluentinc": "USA",
        "@cookpad": "UK",
        "@dailymotion": "France",
        "@dart-lang @flutter @google": "USA",
        "@databricks": "USA",
        "@Datadog": "USA",
        "@DataDog": "USA",
        "@datastax": "USA",
        "@digitalocean": "USA",
        "@docker": "USA",
        "@dropbox": "USA",
        "@Dynatrace": "USA",
        "@eBay": "USA",
        "@elastic": "USA/Dytch",
        "@eldonlabs @google @devcolor": "USA",
        "@EPAM": "USA",
        "@Facebook": "USA",
        "@facebook": "USA",
        "@facebookresearch": "USA",
        "@fastly": "USA",
        "@getsentry": "USA",
        "@github": "USA",
        "@godaddy": "USA",
        "@google": "USA",
        "@google @android": "USA",
        "@google @bazelbuild": "USA",
        "@google @dart-lang @flutter": "USA",
        "@google @golang": "USA",
        "@google @GoogleCloudPlatform": "USA",
        "@google @spinnaker": "USA",
        "@google @tensorflow": "USA",
        "@google Switzerland GmbH": "USA",
        "@google working on @android": "USA",
        "@googleapis": "USA",
        "@GoogleCloudPlatform": "USA",
        "@GoogleCloudPlatform @googleapis @open-telemetry @cloudevents": "USA",
        "@googlers": "USA",
        "@Gradle": "USA",
        "@gradle": "USA",
        "@grafana": "USA",
        "@h2oai": "USA",
        "@hashicorp": "USA",
        "@heroku": "USA",
        "@hortonworks": "USA",
        "@huawei": "China",
        "@IBM": "USA",
        "@IBMResearch": "USA",
        "@Igalia": "Galicia",
        "@implydata": "USA",
        "@influxdata": "USA",
        "@instacart": "USA",
        "@intel": "USA",
        "@JetBrains": "USA",
        "@jetstack": "UK",
        "@kakao": "Korea",
        "@kinvolk": "Germany",
        "@Kitware": "USA",
        "@Kong": "USA",
        "@lightbend": "USA",
        "@LINAGORA": "France",
        "@Linaro": "UK",
        "@line": "Japan",
        "@LinkedIn": "USA",
        "@LLNL": "USA",
        "@lyft": "USA",
        "@mapbox": "USA",
        "@meituan-dianping": "China",
        "@microsoft": "USA",
        "@Microsoft": "USA",
        "@Microsoft @Azure": "USA",
        "@Mirantis": "USA",
        "@moia-dev": "Germany",
        "@mongodb": "USA",
        "@mongodb @10gen": "USA",
        "@Mozilla": "USA",
        "@mozilla": "USA",
        "@mulesoft": "USA",
        "@mysql": "UK",
        "@mysql @oracle": "USA",
        "@naver": "Korea",
        "@NetEase": "China",
        "@netflix": "USA",
        "@Netflix": "USA",
        "@newrelic": "USA",
        "@Nokia": "Finland",
        "@nvidia": "USA",
        "@NVIDIA": "USA",
        "@Oath": "USA",
        "@objectcomputing": "USA",
        "@octoml": "USA",
        "@oracle": "USA",
        "@ovh": "Frace",
        "@paypal": "USA",
        "@pivotal": "USA",
        "@planetscale": "USA",
        "@projectatomic  Red Hat": "USA",
        "@pytorch": "USA",
        "@Quansight": "USA",
        "@reddit": "USA",
        "@redhatofficial": "USA",
        "@robinhood": "USA",
        "@Salesforce": "USA",
        "@SAP": "Germany",
        "@securekey": "Canada",
        "@Shopify": "Canada",
        "@slackhq": "USA",
        "@slalom": "USA",
        "@SpaceExplorationTechnologies": "@google",
        "@splunk": "USA",
        "@spotify": "Sweden",
        "@square": "Japan",
        "@starburstdata": "USA",
        "@stripe": "USA",
        "@SUSE": "Germany",
        "@Talend": "USA",
        "@Target": "USA",
        "@target": "USA",
        "@Tencent": "China",
        "@toptal": "Remote",
        "@twitter": "USA",
        "@twosigma": "USA",
        "@Uber": "USA",
        "@uber": "USA",
        "@Unity-Technologies": "USA",
        "@vercel": "USA",
        "@VerizonMedia": "USA",
        "@ververica": "Germany",
        "@ververica (formerly @dataArtisans)": "Germany",
        "@VMware": "USA",
        "@vmware": "USA",
        "@VMware @heptio": "USA",
        "@wikimedia": "USA",
        "@xiaomi": "China",
        "@Yandex": "Russia",
        "@Yelp": "USA",
        "@zalando": "Germany",
        "@zendesk": "USA",
        "⚡": "China",
        "10gen": "USA",
        "10gen mongodb": "USA",
        "10Gen.com": "USA",
        "42lines": "Japan",
        "6WIND": "France",
        "84.51°": "Wright State University",
        "Aalto University": "Finland",
        "Aarhus University": "Denmark",
        "ACM Class": "Shanghai Jiao Tong U",
        "AdaCore": "France",
        "Adam George - Freelance Software Developer": "FREE",
        "Adobe": "USA",
        "Adobe | Behance": "USA",
        "Adobe Inc": "Apache Cordova",
        "Adobe Inc.": "USA",
        "Adobe Software": "Formerly PhoneGap :(  adobe apache Apache Cordova",
        "Adobe-Marketing-Cloud": "USA",
        "adobe-platform": "USA",
        "Affirm": "USA",
        "agoda-com ThoughtWorks": "USA",
        "Airbnb": "USA",
        "Aiven": "Finland",
        "Aiven Ltd": "Finland",
        "Alauda": "China",
        "Alauda.io": "China",
        "Aleph One Ltd": "UK",
        "Aleph One Ltd.": "UK",
        "Alfresco": "USA",
        "Alfresco Activiti": "USA",
        "Alfresco Software Limited": "USA",
        "Alibaba": "China",
        "Alibaba - 会影": "China",
        "Alibaba alipay apache": "China",
        "alibaba apache": "China",
        "Alibaba Cloud": "China",
        "Alibaba DChain": "China",
        "alibaba dingtalk docs": "China",
        "Alibaba Group": "China",
        "Alibaba Group Holding Limited": "China",
        "Alibaba Groups": "China",
        "Alibaba Inc": "China",
        "Alibaba inc.": "China",
        "Alibaba kubernetes kubernetes-sigs": "China",
        "Alibaba Middleware Team": "China",
        "alibaba taobao": "China",
        "Alibaba-Inc": "China",
        "alibaba-inc.com": "China",
        "alibaba.com": "China",
        "alibaba.inc": "China",
        "alibabaApache": "China",
        "Alipay": "China",
        "alipay sofastack": "China",
        "aliyun": "China",
        "aliyun.com": "China",
        "Allied Telesis Labs": "Japan",
        "Alluxio": "USA",
        "Allwinner Technology Co.": "Ltd.",
        "Altera Corporation": "USA",
        "Amarula Solutions": "Netherlands",
        "Amazon": "USA",
        "Amazon (AWS)": "USA",
        "Amazon Advertising": "USA",
        "Amazon AI": "USA",
        "Amazon Alexa": "USA",
        "Amazon AWS": "USA",
        "AMAZON DEVELOPMENT CENTRE(INDIA) PRIVATE LIMTED": "USA",
        "Amazon Prime Video": "USA",
        "Amazon Research": "USA",
        "Amazon Robotics": "USA",
        "Amazon Web Service": "USA",
        "Amazon Web Service (AI)": "USA",
        "Amazon Web Services": "USA",
        "Amazon Web Services - Machine Learning": "USA",
        "Amazon Web Services (@aws)": "USA",
        "Amazon Web Services (AWS)": "USA",
        "Amazon Web Services aws": "USA",
        "Amazon Web Services Inc.": "USA",
        "Amazon Web Services Japan.": "USA",
        "Amazon.com": "USA",
        "Amazon(amzn) GNOME Foundation(gnome)": "USA",
        "AMD": "USA",
        "AMD Research": "USA",
        "amzn": "USA",
        "Analog Devices Inc": "USA",
        "Andes Technology Corporation": "China",
        "Android  Square": "Japan",
        "Angular.Schule (Freelancer)": "FREE",
        "Ansible by Red Hat": "USA",
        "Ansible Core RedHatOfficial": "USA",
        "Ant Financial": "China",
        "Ant Group alipay": "China",
        "Anyscale": "UC Berkeley",
        "Apache": "USA",
        "apache  tetrateio": "USA",
        "Apache <3": "USA",
        "apache Accelerite": "USA",
        "apache alibaba": "USA",
        "apache amzn": "USA",
        "Apache Bytedance": "China",
        "Apache Databricks": "USA",
        "apache dubbogo mosn sofastack": "USA",
        "apache facebook": "USA",
        "Apache Flink": "USA",
        "apache hortonworks": "USA",
        "apache momo": "USA",
        "apache nineseals": "USA",
        "apache OpenSkywalking": "USA",
        "apache sharding-sphere  elasticjob": "USA",
        "apache shardingjdbc": "USA",
        "Apache Software Foundation": "USA",
        "apache tetrateio": "USA",
        "apache": "inrupt",
        "APM datadog": "USA",
        "Apple": "USA",
        "apple apache": "USA",
        "Apple GmbH": "USA",
        "Apple Inc": "USA",
        "Apple Inc.": "USA",
        "Apple India Pvt Ltd": "USA",
        "Apple netty": "USA",
        "Applemon Technologies": "USA",
        "Applied Scientist  AWS AI": "USA",
        "Aquantia / Marvell": "USA",
        "ArangoDB": "USA",
        "ArangoDB GmbH": "USA",
        "argoproj": "knative",
        "Arista Networks": "USA",
        "aristanetworks": "USA",
        "Arizona State University": "USA",
        "ARM": "UK",
        "Arm @ARMmbed": "UK",
        "Arm ARMmbed": "UK",
        "Arm Holdings": "UK",
        "Arm Limited": "UK",
        "Arm Ltd": "UK",
        "ARM Ltd.": "UK",
        "Arm Treasure Data": "UK",
        "ARM-software": "UK",
        "Armadeus SystemsRockchip Electronics Co.": "Ltd",
        "Asana": "USA",
        "asanarebel": "Germany",
        "asappinc": "Germany",
        "asappinc underarmour myfitnesspal": "Germany",
        "Ask Inline": "Japan",
        "Aspeed Technology Inc": "China",
        "At Red Hat working on @openshift": "USA",
        "At Red Hat working on openshift": "USA",
        "Athens University of Economics and Business": "Greece",
        "Atlassian": "Sydney",
        "atlassian": "ex facebook",
        "Atmel Corporation": "USA",
        "Atos Worldline": "Japan",
        "Australian National University": "Australia",
        "auth0": "USA",
        "Auth0 - auth0": "USA",
        "Auth0": "47C",
        "Autodesk": "USA",
        "Automattic": "USA",
        "Averbis GmbH --- UKP Lab": "Technical University of Darmstadt --- Open Source Developer",
        "Avionic Design": "USA",
        "AWS": "USA",
        "AWS AI": "USA",
        "AWS AI -> Bytedance": "USA",
        "aws awslabs": "USA",
        "aws awslabs amzn": "USA",
        "AWS Cloud9": "USA",
        "AWS Elasticsearch": "USA",
        "aws ICES-EAG mfem": "USA",
        "AWS Labs": "USA",
        "AWS Neo": "USA",
        "AWS Thinkbox": "USA",
        "aws-amplify": "USA",
        "AWS/Redshift/CP": "USA",
        "awsdocs": "USA",
        "awslabs": "USA",
        "awslabs aws": "USA",
        "Azure": "USA",
        "Azure Container Service": "USA",
        "Azure Microsoft": "USA",
        "b-harvest": "USA",
        "B&R Industrial Automation": "Austria",
        "BackMarket": "France",
        "Badoo": "UK",
        "Baidu": "China",
        "Baidu  Inc.": "China",
        "Baidu BDG/IDL/DLTP": "China",
        "Baidu Inc.": "China",
        "Baltic Online Computer GmbH": "Japan",
        "Bangor University": "UK",
        "BayLibre": "France",
        "bbc": "UK",
        "bear-metal Shopify TuneMyGC": "Canada",
        "Beijing Joymond Ltd.": "China",
        "Beijing Mucang Technology Co.": "Ltd.",
        "Beijing University of Posts and Telecommunications": "China",
        "Beijing Zero Light Year Technology Co.": "Ltd.",
        "Bielefeld University": "Germany",
        "bilibili": "China",
        "Biola University": "USA",
        "Biomedicine Discovery Institute": "Monash University",
        "Black Square Media - bsm": "Japan",
        "bliblidotcom apache": "USA",
        "bloodorangeio / bundlebar": "France",
        "Bloomberg": "USA",
        "Bloomberg L.P.": "USA",
        "Bloomberg LP": "USA",
        "Bloomberg LP bloomberg": "USA",
        "BlueprintTech": "UK",
        "bol.com": "Holland",
        "Bolt": "Estonia",
        "boltlearning": "Estonia",
        "Booking.com": "Netherlands",
        "bookingcom": "Netherlands",
        "Booksmart spotify": "Sweden",
        "Booz Allen Hamilton": "USA",
        "Boston University": "USA",
        "Bottomline Technologies": "Japan",
        "Boundary Devices": "USA",
        "Brain Sciences Center: University of Minnesota & Minneapolis VA Medical Center": "USA",
        "brain-research Google-Research": "USA",
        "Braintree": "USA",
        "Breda University of Applied Sciences": "Netherlands",
        "Brightstar Engineering": "USA",
        "Broadcom": "USA",
        "Broadcom Corporation": "USA",
        "Brown University": "USA",
        "ByteDance": "China",
        "Bytedance AI Lab": "China",
        "ByteDance Apache": "China",
        "Bytedance Inc.": "China",
        "Cadence Design Systems Inc": "USA",
        "Cambridge University": "UK",
        "Camunda": "Germany",
        "Camunda Services GmbH": "Germany",
        "Canonical": "UK",
        "Canonical Ltd": "UK",
        "Canonical Ltd.": "UK",
        "CanonicalLtd": "UK",
        "Canva": "USA",
        "Capgemini": "France",
        "Capgemini - Working in Capgemini-AIE": "France",
        "Capital One": "USA",
        "CapitalOne": "USA",
        "capitalone criticalstack": "USA",
        "CapitalOnline": "Japan",
        "Carnegie Mellon University": "USA",
        "Center for Data Science": "Inria",
        "CERN": "USA",
        "Cerner": "USA",
        "chengfayun diditaxi baidu": "China",
        "China": "China",
        "china cmcc": "China",
        "China Mobile": "China",
        "China Mobile (Suzhou) Software Technology Co.": "Ltd.",
        "China Mobile Internet Co.": "Ltd.",
        "China TeleCom": "China",
        "China Unicom": "China",
        "China UnionPay": "China",
        "china-ece": "China",
        "chinac": "China",
        "ChinaMobile": "China",
        "chinaunicom-sri": "China",
        "Chung-Ang University": "South Korea",
        "Cisco": "USA",
        "Cisco China": "China",
        "Cisco Inc.": "USA",
        "Cisco Systems": "USA",
        "Cisco Webex": "USA",
        "citrix": "USA",
        "Citus Data / Microsoft": "USA",
        "Clemson University": "USA",
        "Cloud Infrastructure Engineer kinvolk": "Germany",
        "Cloudbase Solutions": "Romania",
        "CloudBees": "USA",
        "Cloudera": "USA",
        "Cloudera apache": "USA",
        "cloudera hortonworks": "USA",
        "cloudera hortonworks apache": "USA",
        "Cloudera Inc": "USA",
        "Cloudera Inc.": "USA",
        "Cloudflare": "USA",
        "Cloudflare Inc.": "USA",
        "CMU": "Amazon",
        "cncf kubernetes": "USA",
        "Cockroach Labs": "USA",
        "cockroachdb": "USA",
        "cockroachlabs": "USA",
        "codecentric": "Germany",
        "codecentric AG": "Germany",
        "codeuniversity": "USA",
        "cogeco": "Canada",
        "cohere-ai VectorInstitute Google": "USA",
        "Collabora": "UK",
        "Collabora Ltd.": "UK",
        "Collaboration Factory": "UK",
        "Colorado State University csu-chhs": "USA",
        "Columbia University": "USA",
        "Columbia University ccnmtl": "USA",
        "Columbia University in the City of New York": "USA",
        "Comcast": "USA",
        "Compass Electronics Group .LLC": "USA",
        "Compass Electronics Group": "LLC",
        "CompuLab": "Ltd",
        "Computer Science": "University of Toronto",
        "Confluent": "USA",
        "Confluent Inc": "USA",
        "Confluent Inc.": "USA",
        "Confluent/Kafka": "USA",
        "confluentinc": "USA",
        "ConsenSys": "USA",
        "cookpad": "UK",
        "cookpad | AS59128 kmc-jp": "UK",
        "Core-Developer zeebe-io and camunda": "Germany",
        "Cornell University": "USA",
        "Corscience GmbH & Co. KG": "Germany",
        "Couchbase": "USA",
        "CreditEase": "Hulu",
        "Criteo Research (formally at Parietal Team / INRIA)": "France",
        "Currently Nvidia": "USA",
        "Cygnus Software and Google": "USA",
        "CytoVale | Carnegie Melon University": "USA",
        "Czech Technical University": "Czechia",
        "Czech Technical University in Prague": "Czechia",
        "d2iq mesosphere": "USA",
        "dailymotion": "France",
        "Dalhousie University": "Canada",
        "DAMTP": "University of Cambridge",
        "DanmakuPie alibaba": "China",
        "DaoCloud": "China",
        "DaoCloud apache": "USA",
        "dart-lang flutter google": "USA",
        "dasreda.ru": "Russia",
        "DataArt": "USA",
        "dataArtisans": "USA",
        "Databricks": "USA",
        "Databricks Inc.": "USA",
        "databricks netty": "USA",
        "Databricks.com": "USA",
        "Datadog": "USA",
        "DataDog + Mergifyio": "USA",
        "dataPipeline": "Japan",
        "DataStax": "USA",
        "DataStax.com": "USA",
        "ddark008.ru": "Russia",
        "Deakin University": "USA",
        "Debian": "Ubuntu",
        "DeepMind": "UK",
        "Delft University": "Netherlands",
        "Delft University of Technology": "Netherlands",
        "Delivery Hero": "Germany",
        "Delivery Hero SE": "Germany",
        "deliveryhero": "Germany",
        "DeliveryHeroKorea": "Germany",
        "Dell": "USA",
        "Dell / Isilon": "USA",
        "Dell EMC": "USA",
        "DellEMC": "USA",
        "Dharmsinh Desai University": "India",
        "DiDi": "China",
        "DigitalOcean": "USA",
        "digitalocean": "prev shopify",
        "discord": "USA",
        "dmall of china": "China",
        "Docker": "USA",
        "docker (ex-infinit)": "USA",
        "Docker Captain Quintus23M": "USA",
        "Docker Inc.": "USA",
        "dremio": "USA",
        "Dromara apache": "USA",
        "Dropbox": "USA",
        "Dynatrace": "USA",
        "Dynatrace Research": "USA",
        "e-square.io": "Japan",
        "East China Normal University": "China",
        "Easystack": "Singapore",
        "eBay": "USA",
        "eBay Apache": "USA",
        "eBay Inc": "USA",
        "eBay Inc.": "USA",
        "eBayClassifiedsGroup": "USA",
        "ECE  Cornell University": "USA",
        "ecmonline": "Japan",
        "eInfochips Ltd.": "USA",
        "Elastic": "USA/Dytch",
        "Elasticsearch": "USA/Dytch",
        "eldonlabs google devcolor": "USA",
        "Embedded Systems Consultant (Embedded Linux": "ARM micros...)",
        "Emcraft Systems": "USA",
        "eng at twitter": "USA",
        "Engicam": "Italy",
        "eNovance from RedHat from IBM": "USA",
        "Enterasys Networks": "USA",
        "Eötvös Loránd University": "Hungary",
        "EPAM": "USA",
        "EPAM BY": "USA",
        "EPAM Systems": "USA",
        "Epam Systems Inc.": "USA",
        "EPAM Systems LLC": "USA",
        "EPFL": "Switzerland",
        "EPFL Scala Team": "Switzerland",
        "EPFL.ch": "Switzerland",
        "Erasmus University Rotterdam": "Netherlands",
        "Ericsson": "Sweden",
        "eScience lab": "University of Manchester",
        "ETH Zürich": "Switzerland",
        "Etsy": "USA",
        "Ex-Amazonion": "USA",
        "ex-DRW": "ex-ThoughtWorks",
        "Ex-Google": "Blueseed",
        "eXa-online": "Japan",
        "Execonline": "Japan",
        "Expedia": "USA",
        "Expedia Group": "USA",
        "Expedia Inc.": "USA",
        "ExpediaGroup": "USA",
        "ExpediaInc": "USA",
        "Extly Tech & PHP-Prefixer": "Spain",
        "Facebook": "USA",
        "Facebook AI Research": "USA",
        "facebook caffe2 pytorch": "USA",
        "Facebook Inc.": "USA",
        "Facebook PyTorch": "USA",
        "facebook": "ex docker",
        "Faculty at Purdue University": "USA",
        "fairsquarelab": "Japan",
        "Far Eastern Federal University": "Russia",
        "fastbooking.com": "Netherlands",
        "Fastly": "USA",
        "FBK apache": "USA",
        "Federal University of Rio de Janeiro": "Brazil",
        "fedoraproject redhatofficial OSAS": "USA",
        "Flensburg University of Applied Scienes": "Germany",
        "Florida International University": "USA",
        "Flowable": "Switzerland",
        "Flowable AG": "Switzerland",
        "fluxcd for weaveworks": "UK",
        "Flyeralarm GmbH": "UK",
        "FNST(Nanjing Fujitsu Nanda Software Tech. Co.": "Ltd.)",
        "following alibaba": "China",
        "Forio Online Simulations": "Japan",
        "Formerly Foursquare": "Japan",
        "formerly zendesk zopim": "USA",
        "Forter": "USA",
        "FPT University": "Vietnam",
        "freeagent": "Scotland",
        "Freelance": "FREE",
        "Freelance - Senior Software Engineer": "FREE",
        "Freelance Cassandra Developer": "FREE",
        "Freelance clarinetist": "FREE",
        "Freelance consultant": "FREE",
        "Freelance contractor": "FREE",
        "Freelance Data Scientist": "FREE",
        "Freelance Developer": "FREE",
        "Freelance Inc.": "FREE",
        "Freelance Independent": "FREE",
        "Freelance Ruby on Rails developer": "FREE",
        "Freelance Software Developer": "FREE",
        "freelance": "metaclassco",
        "Freelancer": "FREE",
        "Freelancer for hire. Maybe.": "FREE",
        "Freelancer gigster-eng (Gigster)": "FREE",
        "Freelancer Software Development": "FREE",
        "Freescale Semiconductor Inc": "USA",
        "Frontera core developer at scrapinghub": "Ireland",
        "Fuchsia  Google": "USA",
        "Fuchsia @ Google": "USA",
        "Fudan University": "China",
        "fujitsu": "Japan",
        "Fujitsu FNST": "Japan",
        "Fujitsu Laboratories LTD.": "Japan",
        "Fujitsu Ltd.": "Japan",
        "Fujitsu Viet Nam": "Japan",
        "FullStory": "USA",
        "FullStoryDev": "USA",
        "Futura Comunicación Popular. Camsoda. Toptal. fm-futura": "Remote",
        "Gateworks Corporation": "USA",
        "Gdańsk University of Technology": "Poland",
        "General Electric Company": "USA",
        "George Mason University": "USA",
        "Georgia Tech": "formerly SUSTC",
        "getsentry": "USA",
        "GitHub": "USA",
        "GitHub Inc.": "USA",
        "GitHub Semmle lgtmhq": "USA",
        "GitLab": "USA",
        "GitLab Inc.": "USA",
        "gitlab-tokyo dxtokyo": "Japan",
        "gitlabhq": "USA",
        "Glovo": "Spain",
        "GoDaddy": "USA",
        "Gojek": "Indonesia",
        "gojek-engineering": "Indonesia",
        "Google": "USA",
        "Google @googlestadia": "USA",
        "Google AI": "USA",
        "google android": "USA",
        "Google Australia P/L": "USA",
        "google bazelbuild": "USA",
        "Google Brain": "USA",
        "Google Canada": "USA",
        "google dart-lang flutter": "USA",
        "Google Germany GmbH": "USA",
        "Google GmbH": "USA",
        "google golang": "USA",
        "google GoogleCloudPlatform": "USA",
        "Google googlestadia": "USA",
        "GOOGLE INC": "USA",
        "Google Inc.": "USA",
        "Google Japan": "USA",
        "Google Japan G.K. @google": "USA",
        "Google Japan G.K. google": "USA",
        "Google LLC": "USA",
        "Google LLC.": "USA",
        "Google Research": "USA",
        "Google SF": "USA",
        "google spinnaker": "USA",
        "google Switzerland GmbH": "USA",
        "google tensorflow": "USA",
        "Google UK Ltd": "USA",
        "google working on android": "USA",
        "google": "gorilla",
        "Google/YouTube": "USA",
        "googleapis": "USA",
        "GoogleCloudPlatform": "USA",
        "GoogleCloudPlatform googleapis open-telemetry cloudevents": "USA",
        "googlers": "USA",
        "Grad Student UIUC": "Past : Cisco Systems",
        "gradle": "USA",
        "Gradle Inc. (gradle)": "USA",
        "Gradleware": "USA",
        "Graduate Institute of Biomedical Electronics and Bioinformatics": "National Taiwan University",
        "grafana": "USA",
        "Grafana Labs": "USA",
        "Grafana Labs (grafana)": "USA",
        "grafana publiclab ifmeorg": "USA",
        "GSI-HPC": "USA",
        "Guardian Project": "Berkman Center",
        "guestlinelabs": "Japan",
        "Guideline": "Japan",
        "Guntermann & Drunck": "Germany",
        "H2O.ai": "USA",
        "h2oai": "USA",
        "H3C": "China",
        "Hanyang University": "South Korea",
        "Harvard University": "USA",
        "Harvest": "USA",
        "Harvest B.V. / NSX": "USA",
        "Hashicorp": "USA",
        "hashicorp hashicorp-guides  terraform-providers": "USA",
        "Hazelcast": "USA",
        "hazelcast apache": "USA",
        "Heidelberg University": "USA",
        "Helwan University": "Egypt",
        "Heroku": "USA",
        "Heroku / salesforce.com": "USA",
        "heroku & salesforce": "USA",
        "Heroku/Salesforce": "USA",
        "Hewlett Packard Enterprise": "USA",
        "Hewlett Packard Enterprise Galway Ltd": "USA",
        "Hewlett-Packard": "USA",
        "Hewlett-Packard Inc.": "USA",
        "hewlettpackard": "USA",
        "HewlettPackardEnterprise": "USA",
        "HEXKVLT": "influxdata",
        "Hong Kong University of Science and Technology": "USA",
        "Hortonworks": "USA",
        "hortonworks apache cloudera": "USA",
        "Hortonworks Apache Cloudera Flipkart": "USA",
        "hortonworks cloudera": "USA",
        "hortonworks cloudera apache": "USA",
        "hortonworks cloudera uber": "USA",
        "Hortonworks Data Platform": "USA",
        "Hortonworks Inc": "USA",
        "Hortonworks Inc.": "USA",
        "Howard University": "USA",
        "HP": "USA",
        "HP Labs": "USA",
        "HPC Center of Shanghai Jiao Tong University": "USA",
        "HPC devops  BOM": "USA",
        "HPCS Lab.": "University of Tsukuba",
        "HPE": "USA",
        "HPE (hewlettpackard)": "USA",
        "HPE Aruba": "USA",
        "http://gazovik.ru/en/about-us/": "N/A",
        "http://kimmking.github.io": "USA",
        "http://twitter.com/igorribeirolima": "USA",
        "https://apache.org/": "USA",
        "https://cloud.tencent.com/": "China",
        "https://ecararus.github.io/": "USA",
        "https://github.com/99xt": "USA",
        "https://github.com/Alluxio": "USA",
        "https://github.com/facebook": "USA",
        "https://github.com/htmlelements": "USA",
        "https://github.com/NetEase": "USA",
        "https://github.com/PayPal": "USA",
        "https://twitter.com/jarod_liu": "USA",
        "https://www.epam.com/": "USA",
        "https://www.linkedin.com/in/blakelapierre/": "USA",
        "https://www.linkedin.com/in/thomasleplus": "USA",
        "https://www.redhat.com/": "USA",
        "https://www.softwaremill.com": "Poland",
        "HUAWEI": "China",
        "Huawei Dresden Research Center": "China",
        "Huawei Ltd": "China",
        "Huawei Research": "China",
        "Huawei ServiceComb": "China",
        "Huawei Technologies": "China",
        "Huawei Technologies Canada": "China",
        "Huawei Technologies Co. Ltd": "China",
        "Huawei Technologies Co. Ltd.": "China",
        "Huawei Technologies India Pvt Ltd": "China",
        "Huawei Technologies Pvt Ltd": "China",
        "Huawei Technology": "China",
        "HUAWEI technology Ltd.": "China",
        "Huawei-Hadoop": "China",
        "huaweiCloud": "China",
        "huaweicloud  NUAA-Open-Source": "China",
        "Hubspot": "USA",
        "hulu": "USA",
        "HW": "China",
        "hylandsoftware": "USA",
        "HyperCube": "ex-Amazon",
        "IBM": "USA",
        "IBM - Cloudant": "USA",
        "IBM - CODAIT": "USA",
        "IBM and Red Hat": "USA",
        "IBM Center for Open-Source Data and AI Technologies (CODAIT)": "USA",
        "IBM CODAIT": "USA",
        "IBM CODAIT( Formerly IBM Spark Technology Center)": "USA",
        "IBM Corp": "USA",
        "IBM Corp.": "USA",
        "IBM Corporation": "USA",
        "IBM India Pvt. Ltd.": "Red Hat",
        "IBM Japan": "Ltd.",
        "IBM Linux Technology Center": "USA",
        "IBM Pvt. Ltd.": "USA",
        "IBM Reseaerch": "USA",
        "IBM Research": "USA",
        "IBM Research - Tokyo": "Japan",
        "IBM Research & Development GmbH": "USA",
        "IBM Spark Technology Center": "USA",
        "IBM Watson": "USA",
        "IBMResearch": "USA",
        "Igalia": "Galicia",
        "Igalia S.L": "Galicia",
        "ihmeuw (Institute for Health Metrics and Evaluation": "University of Washington)",
        "il-studio.ru": "Russia",
        "Imagination Technologies": "UK",
        "imec - IDLab": "Department of Information Technology",
        "Imply": "USA",
        "Imply Data": "USA",
        "imply.io": "USA",
        "implydata": "USA",
        "Independent": "free",
        "Independent Consultant": "free",
        "Independent consultant/contractor": "free",
        "Independent Contractor": "free",
        "Independent Software Developer": "free",
        "Independent Software Engineer": "free",
        "Independent VM Hacker & Faculty of Information Technologies": "Czech Technical University in Prague",
        "InfluxData": "USA",
        "Information Center of MNR China": "China",
        "Inria": "France",
        "Inria - Parietal team": "France",
        "Inria - Saclay": "France",
        "INRIA Saclay - Parietal team": "France",
        "Inria Saclay – Île-de-France": "France",
        "inspur": "China",
        "Instacart": "USA",
        "Instana": "USA",
        "Institute for Protein Design": "University of Washington",
        "Intel": "USA",
        "Intel - 01org": "USA",
        "Intel - OTC Linux Graphics": "USA",
        "Intel Asia-Pacific R&D": "USA",
        "Intel Corp": "USA",
        "Intel Corpoartion": "USA",
        "Intel Corporation": "USA",
        "Intel Open Source Technology Center": "USA",
        "Intel OTC": "USA",
        "Intel Technology Poland": "USA",
        "Intel Tencent": "USA",
        "intel": "Lobachevsky University",
        "Intentionet": "USA",
        "International Business Machines Corp": "USA",
        "Intuit": "USA",
        "Iowa State University": "USA",
        "Istituto di Scienza e Tecnologie dell'Informazione - CNR": "USA",
        "IT Freelancer": "FREE",
        "ITMO University": "197101",
        "ivi.ru": "Russia",
        "JBoss by Red Hat": "USA",
        "JBoss by Red Hat by IBM": "USA",
        "JD": "China",
        "JD apache": "China",
        "JD apache shardingsphere": "China",
        "JD Digit": "China",
        "JD.com": "China",
        "JDCTeam": "China",
        "JDriven": "China",
        "jdwl": "China",
        "JDYun": "China",
        "Jegiellonian University": "Poland",
        "JetBrains": "USA",
        "jetstack": "UK",
        "jkakar-stripe": "USA",
        "JMG Robotics": "dronecrew.com",
        "Johannes Kepler University Linz": "Austria",
        "Johns Hopkins University": "USA",
        "Johns Hopkins University - Department of Biology": "USA",
        "Johns Hopkins University Applied Physics Laboratory": "USA",
        "Juniper Networks": "USA",
        "Kakao": "Korea",
        "Kakao Corp": "Korea",
        "Kakao Corporation": "Korea",
        "kakao enterprise": "Korea",
        "Kakao Inc.": "Korea",
        "kakao payw-org": "Korea",
        "KakaoBank": "Korea",
        "KakaoEnterprise": "Korea",
        "kakaoicloud": "Korea",
        "Kakaopay corp": "Korea",
        "Kansas State University": "USA",
        "Karlsruhe University of Applied Sciences": "Germany",
        "Karlstad University": "Sweden",
        "KeepTruckin": "USA",
        "Keymile AG": "Germany",
        "kinvolk": "Germany",
        "Kitware": "USA",
        "Kitware Inc.": "USA",
        "klausapp": "Germany",
        "Kobe University": "Japan",
        "Kong": "USA",
        "Kong Inc": "USA",
        "Kong Inc.": "USA",
        "kubermatic": "USA",
        "kubernetes": "USA",
        "kubernetes | ex-kyma-project": "USA",
        "kubernetes istio  servicemesher": "USA",
        "kubernetes weaveworks": "UK",
        "kubernetes-sigs kubernetes": "USA",
        "Laikipia University": "Kenya",
        "LAMP / EPFL": "Switzerland",
        "lampepfl": "Switzerland",
        "Lancaster University": "UK",
        "Lawrence Livermore National Laboratory": "USA",
        "Lead Developer InnoDB MariaDB": "USA",
        "LeanFive": "ArangoDB",
        "Leiden University": "Netherlands",
        "Let's Delivery": "Brazil",
        "LG CNS": "Korea",
        "LG Electronics": "Korea",
        "Lightbend": "USA",
        "Lightbend Inc": "USA",
        "Lightbend Inc.": "USA",
        "lightbend typesafehub": "USA",
        "Linagora": "France",
        "Linagora VietNam": "France",
        "Linaro": "UK",
        "Linaro Limited": "UK",
        "Linaro Ltd.": "UK",
        "LINE": "Japan",
        "LINE Corp": "Japan",
        "LINE Corporation": "Japan",
        "LINE Fukuoka": "Japan",
        "Line Thailand": "Japan",
        "line+": "Japan",
        "LinkedIn": "USA",
        "linkedin apache": "USA",
        "Linkedin Corporation": "USA",
        "LinkedIn!": "USA",
        "Linköping University": "Sweden",
        "LLNL": "USA",
        "Lund University": "Sweden",
        "Lund University Cancer Center": "Sweden",
        "Lyft": "USA",
        "Lyft (ex-Google/YT": "ex-DanceDeets)",
        "Lyft Level 5": "USA",
        "Machine Intelligence Research Institute": "USA",
        "Magikcraft Camunda Zeebe-io": "Germany",
        "Mail.Ru": "Russia",
        "Mapbox": "USA",
        "MariaDB": "USA",
        "MariaDB Corporation": "USA",
        "MariaDB Corporation Ab": "USA",
        "MariaDB Foundation": "USA",
        "MariaDB Services Ab": "USA",
        "mariadb-corporation": "USA",
        "Marvell": "USA",
        "Marvell International Ltd": "USA",
        "Marvell International Ltd.": "USA",
        "Marvell Semiconductor": "USA",
        "Mastercard": "USA",
        "Masters Student at Stony Brook University": "USA",
        "Max Planck Institute for Dynamics and Self-Organization": "FREE",
        "McGill University": "Canada",
        "Mediatek": "China",
        "MediaTek Inc": "China",
        "meituan": "China",
        "meituan-dianping": "China",
        "meituan.com": "China",
        "Mellanox": "Israeli-USA",
        "Mellanox Technologies": "Israeli-USA",
        "mention https://github.com/zendesk": "USA",
        "Mentor Graphics": "USA",
        "Mentor Graphics Corporation": "USA",
        "Menttis": "UK",
        "Mercari": "Japan",
        "mercari and merpay": "Japan",
        "Mercari JP": "Japan",
        "mercari merpay": "Japan",
        "Mesosphere": "USA",
        "Meteor/Apollo (formerly: Facebook/Instagram": "Quora",
        "MGM": "Haukeland University Hospital",
        "mhackeroni TheRomanXpl0it": "Netherlands",
        "Michigan State University": "USA",
        "Microchip Technology Inc.": "USA",
        "Microsemi Corporation": "USA",
        "Microsoft": "USA",
        "Microsoft - CISL": "USA",
        "Microsoft (Semantic Machines)": "USA",
        "Microsoft / microsoft": "USA",
        "Microsoft Azure": "USA",
        "Microsoft Azure deislabs": "USA",
        "Microsoft Bot Framework": "USA",
        "microsoft citusdata": "USA",
        "Microsoft Corp.": "USA",
        "Microsoft Corporation": "USA",
        "Microsoft Healthcare / Harvard Medical School / Boston Children's Hospital": "USA",
        "Microsoft Mobile Innovation Lab": "USA",
        "Microsoft MVP": "USA",
        "Microsoft on TypeScript": "USA",
        "Microsoft Project at ASAL Technologies": "USA",
        "Microsoft Purdue": "USA",
        "Microsoft Quantum Hardware": "USA",
        "Microsoft Research": "USA",
        "Microsoft Research Asia": "USA",
        "Microsoft: Azure Group": "USA",
        "Microsoft/Glimpse": "USA",
        "MicrosoftCitus": "USA",
        "Migros Online AG": "Japan",
        "Minnesota State University Moorhead": "USA",
        "Minnesota Supercomputing Institute": "University of Minnesota",
        "Mirantis": "USA",
        "MIT": "USA",
        "MIT CSAIL": "USA",
        "MIT Lincoln Laboratory": "USA",
        "mit-lcp": "USA",
        "Mitchell Humphrey & Co.": "USA",
        "mitre": "USA",
        "Mittwald CM Service (mittwald)": "USA",
        "ML at ExpediaGroup": "USA",
        "Mobile Robotics Lab": "McGill University",
        "MOIA": "Germany",
        "moia-dev": "Germany",
        "Monash University": "Australia",
        "moneyforward && Kobe university": "Japan",
        "MongoDB": "USA",
        "mongodb 10gen": "USA",
        "MongoDB Inc.": "USA",
        "MontaVista Software": "USA",
        "Moravia Microsoft": "USA",
        "Moscow State University": "119991",
        "Mozilla": "USA",
        "Mozilla (mozilla)": "USA",
        "Mozilla Corp": "USA",
        "Mozilla Corporation": "USA",
        "MPL AG": "Switzerland",
        "MuleSoft": "USA",
        "MuleSoft / Salesforce": "USA",
        "Mulesoft Salesforce": "USA",
        "Münster University of Applied Sciences": "Germany",
        "MySelf": "FREE",
        "mysql": "UK",
        "MySQL (Oracle)": "USA",
        "mysql at Oracle Corp.": "USA",
        "MySQL NDB Cluster": "UK",
        "mysql oracle": "USA",
        "N/A": "N/A",
        "N26": "Germany",
        "Nanjing University": "China",
        "Nanjing University of Aeronautics and Astronautics": "China",
        "Nankai University": "300071",
        "Nanyang Technological University": "Singapore 639798",
        "NASA Goddard Space Flight Center": "USA",
        "National Chiao Tung University": "China",
        "National Instruments": "USA",
        "National Taiwan University": "China",
        "National University of Singapore": "Singapore",
        "Naver": "Korea",
        "NAVER AI Lab": "Korea",
        "Naver Clova": "Korea",
        "Naver Corp": "Korea",
        "Naver Corp.": "Korea",
        "NAVER Forest CIC": "Korea",
        "NEC": "Japan",
        "NEC Laboratories Europe GmbH": "Japan",
        "NEC Solution Innovators": "Ltd.",
        "NEC Technologies": "Japan",
        "NEC Technologies Ind. Pvt. Ltd": "Japan",
        "NEC Technologies India pvt. limited": "Japan",
        "Nectar Research Cloud": "University of Melbourne",
        "Neo Technology (neo4j)": "USA",
        "neo4j": "USA",
        "NetApp": "USA",
        "NetEase": "China",
        "NetEase apache": "USA",
        "Netease Games": "China",
        "netease Hangzhou Institute": "China",
        "Netfarm S.r.l.": "UK",
        "Netflix": "USA",
        "Netflix  nebula-plugins": "USA",
        "Netflix Inc.": "USA",
        "netflix": "ex-cloudera",
        "New York University": "USA",
        "newrelic": "USA",
        "NewsBreak": "Facebook",
        "Nexell Co.": "Ltd",
        "NGINX": "USA",
        "NGINX Inc": "USA",
        "NGINX Inc.": "USA",
        "nginxinc": "USA",
        "nightech": "Freelance",
        "Nirma University": "India",
        "no.linkedin.com/in/blomsoy/no": "USA",
        "Nokia": "Finland",
        "Nokia Corporation": "Finland",
        "nokia-wroclaw": "Finland",
        "Northeastern University": "USA",
        "Norwegian University of Science and Technology": "SINTEF Medical Technology",
        "Novosibirsk State University": "630090",
        "NTT": "UK",
        "NTT Communications": "UK",
        "NTT DATA": "UK",
        "NTT DATA Corporation": "UK",
        "NTT Data GDS": "UK",
        "NTT Lab.": "UK",
        "NTTi3/NTTLab": "UK",
        "Nuagenetworks": "Nokia",
        "nubank": "USA",
        "NUVIA Inc": "France",
        "NuVia Inc.": "France",
        "NVIDIA": "USA",
        "NVIDIA / Technion": "USA",
        "NVIDIA AI": "USA",
        "nvidia corporation": "USA",
        "NVIDIA Gmbh": "USA",
        "Nvidia/PGI": "USA",
        "NXP": "Netherlands",
        "NXP India Pvt. Ltd.": "Netherlands",
        "NYU Shanghai": "China",
        "Oak Ridge National Laboratory": "Switzerland",
        "Oath": "USA",
        "oath / yahoo": "USA",
        "Object Computing (objectcomputing)": "USA",
        "objectcomputing": "USA",
        "OctoML": "USA",
        "OctoML Inc": "USA",
        "Ohio State University": "USA",
        "Ohio University": "USA",
        "ohmu aiven": "Finland",
        "okta": "USA",
        "Omicron Ceti AB": "Sweden",
        "Online Reporting Inc. (FileTrac)": "Japan",
        "Open Source / Freelancer": "FREE",
        "Open Source Apple": "USA",
        "OpenJDK engineer oracle": "USA",
        "openlawteam ConsenSys": "USA",
        "openSUSE": "Germany",
        "OPPO": "China",
        "oppo.com": "China",
        "ops-baidu mongodb": "China",
        "Oracle": "USA",
        "Oracle - ODC": "USA",
        "Oracle Corp (MySQL Engineering)": "USA",
        "Oracle Corp.": "USA",
        "Oracle Corporation": "USA",
        "Oracle India Private Limited": "USA",
        "Oracle India Pvt. Ltd.": "USA",
        "oracle javaee": "USA",
        "Oracle JavaEE GlassFish Eclipse-EE4J": "USA",
        "Oracle Labs": "USA",
        "Oraclelabs": "USA",
        "Orange": "France",
        "Orange Labs": "France",
        "Orange R&D Lab": "France",
        "Orange-Application-for-Business": "France",
        "Orangedox": "France",
        "OrangeLV": "France",
        "Oregon State University": "USA",
        "Outsmartly": "prev Netflix",
        "OVH": "Frace",
        "Ozon": "Russia",
        "Ozon.ru": "Russia",
        "ozonru": "Russia",
        "Paceline": "Japan",
        "Paderborn University": "Germany",
        "Palantir": "USA",
        "Panasonic Corporation": "Japan",
        "Pardot Salesforce": "USA",
        "Paris-Saclay University": "France",
        "PayPal": "USA",
        "PayPal Inc.": "USA",
        "PayPal/Braintree": "USA",
        "Pekin' University": "USA",
        "Peking University": "USA",
        "Pelion": "an ARM company",
        "PelionIoT": "USA",
        "PelionIoT ArmMbedCloud  AsyncNetwork": "USA",
        "pengutronix": "Germany",
        "pexip": "Norway",
        "Pexip AS": "Norway",
        "Phil Blundell Consulting Ltd": "USA",
        "PHPLift.net": "Spain",
        "phpmyadmin": "wdes",
        "PingCAP": "USA",
        "Pinterest": "USA",
        "pinterest (fmrly square)": "USA",
        "Pivotal": "USA",
        "Pivotal  VMware": "USA",
        "Pivotal / Cloud Foundry": "USA",
        "pivotal-cf": "USA",
        "pivotal-cf vmware": "USA",
        "planetscale": "USA",
        "plangrid Autodesk": "USA",
        "Platform Engineer  bol.com": "Holland",
        "Playtika": "Israel",
        "Predella": "USA",
        "Princeton University": "USA",
        "PrincetonUniversity": "USA",
        "Production Engineer Shopify": "Canada",
        "projectatomic  Red Hat": "USA",
        "prometheus gitlabhq": "USA",
        "propheads propellerheadsar whyline": "Japan",
        "Psyent Corporation": "USA",
        "Purdue University": "USA",
        "pytorch": "USA",
        "Quansight": "USA",
        "Quansight Labs": "USA",
        "Quansight-Labs": "USA",
        "Qubole": "USA",
        "Queensland University of Technology": "Australia",
        "R&D Fujitsu Poland": "Japan",
        "Rackspace": "USA",
        "Rackspace (rackerlabs)": "USA",
        "Rackspace | Cleartech Software LLC": "USA",
        "Rackspace Technology": "USA",
        "Rackspace: The Open Cloud Company": "USA",
        "Rangsit University": "Thailand",
        "Red Hat - @hibernate": "USA",
        "Red Hat - @openshift": "USA",
        "Red Hat - hibernate": "USA",
        "Red Hat - IBM": "USA",
        "Red Hat - openshift": "USA",
        "Red Hat - Openstack Core Developer": "USA",
        "Red Hat @AICoE": "USA",
        "Red Hat @RedHat": "USA",
        "Red Hat & Blazebit": "USA",
        "Red Hat | CU Boulder": "USA",
        "Red Hat A/S": "USA",
        "Red Hat AICoE": "USA",
        "Red Hat Canada Ltd.": "USA",
        "Red Hat Czech": "s.r.o.",
        "Red Hat Gmbh": "USA",
        "Red Hat Inc": "USA",
        "Red Hat Inc.": "USA",
        "Red Hat India Pvt Ltd": "USA",
        "Red Hat K.K.": "USA",
        "Red Hat RedHat": "USA",
        "Red Hat UK": "USA",
        "reddit": "USA",
        "Redfish Solutions": "LLC",
        "redhat-openstack": "USA",
        "redhat-openstack ansible openstack containers": "USA",
        "RedHatEMEA redhatNORDICS": "USA",
        "redhatofficial": "USA",
        "RedHatOfficial gluster": "USA",
        "Redpill Linpro": "Sweden",
        "Redpill-Linpro": "Sweden",
        "Renesas Electronics Corporation": "Japan",
        "Research Assistant at Aalto University": "Finland",
        "ResearchGate / thePHP Website / PODEntender / Eigenart Magazin": "Spain",
        "Rice University": "USA",
        "RISC-V Ambassador / Red Hat": "USA",
        "robinhood": "USA",
        "robinhoodmarkets": "USA",
        "Rockchip Electronics Co.": "Ltd",
        "Route42 & freelance": "FREE",
        "Royal Holloway": "University of London",
        "Russian University of Transport": "Russia",
        "Rutgers University": "USA",
        "RWTH Aachen University": "Germany",
        "S7 Airlines": "Japan",
        "Saint Petersburg State University of Aerospace Instrumentation": "190000",
        "Salesforce": "USA",
        "Salesforce Commerce Cloud": "USA",
        "salesforce": "cmu-db",
        "Salesforce.com": "USA",
        "Salesforcel": "USA",
        "Samsung": "Korea",
        "samsung adgear": "Korea",
        "Samsung Electronics": "Korea",
        "Samsung Electronics Co.": "Korea",
        "Samsung Electronics HQ": "Korea",
        "Samsung Electronics Moscow research center": "Korea",
        "Samsung Electronics Samsung": "Korea",
        "Samsung Electronics Ukraine Company": "Korea",
        "Samsung SDS": "Korea",
        "Samsung SDS R&D": "Korea",
        "SAP": "Germany",
        "SAP Cloud Infrastructure": "Germany",
        "SAP Concur": "ex GoodData",
        "SAP Hybris": "Germany",
        "SAP Labs": "Germany",
        "SAP SE": "Germany",
        "SAP UK Ltd": "Germany",
        "Sapient": "Germany",
        "SapientNitro": "Germany",
        "Sartura Ltd": "Croatia",
        "SAS": "USA",
        "Schuberg Philis": "USA",
        "schubergphilis": "USA",
        "Scikit-learn  Inria foundation": "France",
        "Scoville / Tokyo Institute of Technology": "Japan",
        "ScrapingHub": "Ireland",
        "ScyllaDB": "USA",
        "SD DataSolutions GmbH": "Apache Software Foundation",
        "SDE - Amazon Athena": "USA",
        "securekey": "Canada",
        "SecureKey Technologies": "Canada",
        "SecureKey Technologies Inc.": "Canada",
        "segmentio": "USA",
        "self": "FREE",
        "self - deli clerk": "FREE",
        "Self employed": "FREE",
        "Self Employed Consultant": "FREE",
        "Self Employed": "CTO at eyedo fielding technologies ltd.",
        "Self-Employed": "FREE",
        "self-employed": "teacher at MIREA",
        "Self-employment": "FREE",
        "Semmle github": "USA",
        "Senior Kubernetes Architect vmware": "USA",
        "Sentry": "USA",
        "Seoul National University": "Korea",
        "Sfeir": "France",
        "Shanghai Engineering Research Center for Broadband Networks and Applications": "China",
        "Shanghai Jiao Tong University": "China",
        "Shanghai JiaoTong University": "China",
        "ShanghaiTech University": "China",
        "Shopee": "Singapore",
        "Shopee Singapore": "Singapore",
        "Shopify": "Canada",
        "Shopify (as casperisfine)": "Canada",
        "Sichuan University": "China",
        "Siemens": "Germany",
        "Siemens AG": "Germany",
        "Siemens Corporate Technology": "Germany",
        "Siemens CT": "Germany",
        "sifive": "USA",
        "sifive riscv ucb-bar": "USA",
        "Simon Fraser University": "Canada",
        "Simply Business": "UK",
        "simplybusiness": "UK",
        "simplymeasured sproutsocial": "USA",
        "SJTU/Tencent/INTEL": "China",
        "skyapm apache": "USA",
        "Skyscanner": "Scotland",
        "Skyward (Verizon)": "Totaal Software",
        "Slack": "USA",
        "slackapi and unioncode": "USA",
        "slackhq": "USA",
        "SlackHQ SlackAPI": "USA",
        "slalom": "USA",
        "SlamData": "USA",
        "Snap Inc.": "USA",
        "snap40": "USA",
        "SnapBill": "USA",
        "snapbytes": "Turkey",
        "Snapchat": "USA",
        "SnapLogic": "USA",
        "Snapp-Mobile": "USA",
        "Snapp!": "USA",
        "Snappy Apps": "USA",
        "SnapShot GmbH": "USA",
        "snapt": "USA",
        "Snapyr": "USA",
        "Socionext Inc": "Japan",
        "Software Developer": "Canva",
        "Software Engineer @google": "USA",
        "Software engineer DataDog working on Vector": "USA",
        "Software Engineer google": "USA",
        "SoftwareMill": "Poland",
        "softwaremill.com": "Poland",
        "Sogou / Thoughtworks": "USA",
        "Sony": "Japan",
        "Sony Interactive Entertainment": "Japan",
        "Soochow University": "China",
        "SouchProd": "Paris",
        "soujava apache eclipse-ee4j": "USA",
        "South China Normal University": "China",
        "South China University of Technology": "China",
        "Southeast University.CN": "USA",
        "Southern Oregon University": "USA",
        "Southern University of Science and Technology": "China",
        "SpaceExplorationTechnologies": "google",
        "Splunk": "USA",
        "Splunk Inc.": "USA",
        "Spotify": "Sweden",
        "Spotify AB": "Sweden",
        "Spotify née The Echo Nest": "Sweden",
        "Spotify USA": "Sweden",
        "SpringSource by Pivotal": "USA",
        "sqlcollaborative web2py": "UK",
        "Square": "Japan",
        "Square Inc": "Japan",
        "Square Inc.": "Japan",
        "SquareGPS": "Japan",
        "Squarepoint Capital": "Japan",
        "squarespace": "Japan",
        "squareup": "Japan",
        "Stack.Build": "SAP",
        "stackhpc": "USA",
        "StackHPC Ltd": "USA",
        "Stanford University": "USA",
        "Starburst": "USA",
        "Starburst Data": "USA",
        "starburstdata": "USA",
        "Stasosphere Online Inc.": "Japan",
        "steprz apache": "USA",
        "STMicroelectronics": "Switzerland",
        "Stockholm University / Scilifelab": "Sweden",
        "stony brook university": "USA",
        "Stratio": "Spain",
        "StratioBD": "Spain",
        "Stripe": "USA",
        "Sun Yat-sen University": "China",
        "Sundell Open Source Consulting AB": "USA",
        "SUSE": "Germany",
        "SUSE Labs": "Germany",
        "SUSE Linux": "Germany",
        "SUSE Linux GmbH": "Germany",
        "SUSE openSUSE gphoto": "Germany",
        "SUSE Software Solutions Germany GmbH": "Germany",
        "SUSTC": "China",
        "Sydney Informatics Hub": "University of Sydney",
        "Syracuse University": "USA",
        "Sysgo Real-Time Solutions": "GmbH",
        "SZTE": "China",
        "Talend": "USA",
        "Talend Inc.": "USA",
        "taobao": "China",
        "taobao alibaba": "China",
        "taobao tmall aliyun alibaba": "China",
        "Taobao.com": "China",
        "Target": "USA",
        "Target Corporation": "USA",
        "teamdigitale": "USA",
        "teamsnap": "USA",
        "Technexion Ltd": "China",
        "Technical University of Catalonia": "Spain",
        "Technical University of Košice": "Slovakia",
        "Technical University of Munich": "Germany",
        "Temple University": "USA",
        "Ten Square Games S.A.": "Japan",
        "Tencent": "China",
        "Tencent.com": "China",
        "TencentCloud": "China",
        "Tensilica Inc": "USA",
        "Teradata": "USA",
        "Teradata Spain": "USA",
        "Tesla (ex NVIDIA)": "USA",
        "testcontainers": "apache",
        "Texas Instruments": "USA",
        "Texas Instruments Incorporated": "USA",
        "The Android Open Source Project": "USA",
        "The Apache Software Foundation": "USA",
        "The Dark Art of Coding | Booz Allen Hamilton": "USA",
        "The DataLab": "Oxford University",
        "The George Washington University": "USA",
        "The Hacker's Choice | mh-sec | me | myself": "FREE",
        "The Johns Hopkins University": "USA",
        "The Line": "Llc",
        "The Ohio State University": "USA",
        "The University of Auckland": "New Zealand",
        "The University of Texas at Austin": "USA",
        "the University of Tokyo": "Japan",
        "The University of Tokyo / riken-aip": "Japan",
        "The University of Washington eScience Institute": "USA",
        "Theobroma Systems Design und Consulting": "Austria",
        "Thoughtworks": "USA",
        "ThoughtWorks Inc.": "USA",
        "ThoughtWorksInc": "USA",
        "Thread": "prev YPlan",
        "Tianjin University": "China",
        "tibco": "paypal",
        "Timesys Corporation": "USA",
        "Tinkoff.ru": "Russia",
        "TNG": "Malaysia",
        "TNG Technology Consulting": "Malaysia",
        "TNG Technology Consulting GmbH": "Malaysia",
        "Toby Churchill Ltd": "UK",
        "Tokyo Institute of Technology / traPtitech": "Japan",
        "Tokyo Metropolitan University": "Japan",
        "TomTom": "Holland",
        "tomtom-international": "Holland",
        "toolchainlabs pantsbuild apache perkuno": "USA",
        "toptal": "Remote",
        "Toradex AG": "Switzerland",
        "Torchbox": "UK",
        "torchbox wagtail": "UK",
        "Touchline Interactive": "Japan",
        "TQ-Systems": "Germany",
        "Trail of Bits": "USA",
        "trailofbits": "USA",
        "Trainee and freelancer": "FREE",
        "TransferWise": "UK",
        "trinodb starburstdata": "USA",
        "TsiChung Liew": "USA",
        "Tsinghua University": "China",
        "Tsinghua University tuna Association": "China",
        "TU Dortmund University": "Germany",
        "Tulane University": "USA",
        "Twilio": "USA",
        "Twitter": "USA",
        "Twitter Inc.": "USA",
        "Twitter: davkals": "USA",
        "Twitter: fresskoma": "USA",
        "Twitter.com": "USA",
        "twosigma": "USA",
        "TwoSigma Investments": "USA",
        "Uber": "USA",
        "Uber AI Labs": "USA",
        "Uber ATG": "USA",
        "uber fossasia": "USA",
        "Uber Freight": "USA",
        "uber pizzahutdigital": "USA",
        "Uber Technology Inc": "USA",
        "uber uber-atg": "USA",
        "uber uber-atg uber-research": "USA",
        "uber-atg": "USA",
        "uberall GmbH": "USA",
        "Uberu": "LLC",
        "UC Berkeley": "USA",
        "UC Berkeley ucbrise": "USA",
        "UESTC": "China",
        "Ulm University": "USA",
        "Unicode": "AWS",
        "Unity Technologies": "USA",
        "Unity-Technologies": "USA",
        "University at Buffalo": "USA",
        "University College London": "UK",
        "University Computer Club": "Canada",
        "University of Alberta": "Canada",
        "University of Amsterdam": "Netherlands",
        "University of Arizona": "USA",
        "University of Arkansas for Medical Sciences": "USA",
        "University of Bialystok": "Poland",
        "University of Birmingham": "UK",
        "University of Bologna": "Italy",
        "University of Bonn FASTGenomics": "Germany",
        "University of British Columbia": "Canada",
        "University of Calgary": "Canada",
        "University of California": "USA",
        "University of California - Berkeley": "USA",
        "University of California Riverside": "USA",
        "University of California San Francisco": "USA",
        "University of Cambridge": "UK",
        "University of Cambridge (CTSRD-CHERI)": "UK",
        "University of Campinas": "cloudflare",
        "University of Canterbury": "USA",
        "University of Central Lanchasire": "UK",
        "University of Chicago": "USA",
        "University of Colorado Boulder": "USA",
        "University of Connecticut": "USA",
        "University of Debrecen": "Hungary",
        "University of Edinburgh": "UK",
        "University of Florida": "USA",
        "University of Geneva": "Switzerland",
        "University of Genoa": "Italy",
        "University of Glasgow": "UK",
        "University of Graz": "Austria",
        "University of Groningen": "Netherlands",
        "University of Hawaii": "USA",
        "University of Helsinki": "Finland",
        "University of Idaho": "USA",
        "University of Illinois": "USA",
        "University of Illinois at Urbana Champaign": "USA",
        "University of Illinois at Urbana-Champaign": "USA",
        "University of illinois Urbana Champaign": "USA",
        "University of Kansas": "USA",
        "University of Leipzig": "Germany",
        "University of Lille": "France",
        "University of Luxembourg": "Luxembourg",
        "University of Málaga": "Spain",
        "University of Malta": "Malta",
        "University of Manchester": "UK",
        "University of Massachusetts Amherst": "USA",
        "University of Melbourne": "Australia",
        "University of Michigan": "USA",
        "University of Minnesota": "USA",
        "University of Murcia": "Spain",
        "University of New Brunswick": "USA",
        "University of Newcastle": "Australia",
        "University of Oslo": "Norway",
        "University of Oxford": "UK",
        "University of Passau": "Germany",
        "University of Pennsylvania": "USA",
        "University of Pittsburgh": "USA",
        "University of Pittsburgh Medical Center": "USA",
        "University of Rochester": "USA",
        "University of San Francisco": "USA",
        "University of Science & Technology of China": "China",
        "University of South-Eastern Norway": "Norway",
        "University of Southern California": "USA",
        "University of Southern Denmark": "Denmark",
        "University of St Andrews": "OvGU Magdeburg",
        "University of Stavanger": "Norway",
        "University of Sussex": "UK",
        "University of Szeged": "Hungary",
        "University of the Philippines": "Philippines",
        "University of Tokyo": "Japan",
        "University of Toronto": "Canada",
        "University of Trento": "Italy",
        "University of Utah": "USA",
        "University of Warwick": "UK",
        "University of Washington": "USA",
        "University of Waterloo": "Canada",
        "University of Westminster": "USA",
        "University of Wisconsin-Madison": "USA",
        "Upper Austria University of Applied Sciences": "Austria",
        "Uppsala University": "Sweden",
        "USTC": "China",
        "Utah State University": "USA",
        "UTokyo": "Japan",
        "Vanderbilt University": "USA",
        "vanilophp": "Spain",
        "vercel": "USA",
        "Verizon": "USA",
        "Verizon Digital Media Services": "USA",
        "Verizon Media": "USA",
        "Verizon Media (formerly Yahoo)": "USA",
        "VerizonMedia": "USA",
        "Ververica": "Germany",
        "ververica (formerly dataArtisans)": "Germany",
        "Ververica GmbH": "Germany",
        "viabtc tencent": "China",
        "vimeo": "USA",
        "VirtusLab": "poland",
        "VMware": "USA",
        "vmwarepivotallabs": "USA",
        "Volunteer at (ISC)² Safe and Secure Online": "Japan",
        "VS Code & Microsoft": "USA",
        "Walmart": "USA",
        "Walmart India": "USA",
        "Walmart Labs": "USA",
        "walmartlabs": "USA",
        "Waseda University": "Japan",
        "Washington State University": "USA",
        "Washington University in Saint Louis": "USA",
        "Washington University in St. Louis": "USA",
        "weaveworks": "UK",
        "Western Digital": "USA",
        "Western Digital Corporation": "USA",
        "WhatsApp": "Germany",
        "wikimedia": "USA",
        "Wikimedia Foundation": "USA",
        "wikimedia smc": "USA",
        "WillBooser Inc. / Waseda University": "Japan",
        "William-Hill-Online": "Japan",
        "Wind River": "USA",
        "windriver": "USA",
        "Wix": "Israel",
        "Workday": "USA",
        "Working at VMware Inc": "Contributing to Apache Software Foundation",
        "worldline": "Japan",
        "Wuhan University": "China",
        "www.alipay.com": "China",
        "www.ecp.ru": "Russia",
        "www.fly-server.ru": "Russia",
        "www.meituan.com": "China",
        "Xen Project": "Citrix",
        "xiaomi": "China",
        "XiaoMi Tencent": "China",
        "xidian University": "China",
        "xilinx": "USA",
        "Xilinx Inc.": "USA",
        "xpbrew freelancer": "FREE",
        "Yahoo": "USA",
        "Yahoo / Verizon Media": "USA",
        "Yahoo Inc": "USA",
        "Yahoo Japan Corporation": "USA",
        "yahoo VerizonMedia aol": "USA",
        "Yahoo!": "USA",
        "Yahoo! Inc": "USA",
        "Yahoo! Inc.": "USA",
        "Yahoo! JAPAN": "USA",
        "Yahoo!/Oath/VerizonMedia": "USA",
        "Yandex": "Russia",
        "Yandex LLC": "Russia",
        "yandex-cloud": "Russia",
        "YandexClassifieds": "Russia",
        "Yelp": "USA",
        "Yitu Singapore": "Singapore",
        "York University": "Canada",
        "yorkie-team summernote naver": "Korea",
        "Zalando": "Germany",
        "Zalando SE": "Germany",
        "zapier": "USA",
        "Zé Delivery": "Brazil",
        "Zendesk": "USA",
        "Zenika": "France",
        "Zhejiang University": "China",
        "Zilverline": "Japan",
        "Zilverline B.V.": "Japan",
        "ZTE": "China",
        "ZTE Corporation": "China",
        "ZTE-PaaS": "China",
        "ztech-company": "China",
        "Ꮐооցⅼе": "USA",
        "네무스텍": "China",
        "뉴비 주식회사": "China",
        "식스샵": "China",
        "上海群之脉信息科技有限公司": "China",
        "中国": "China",
        "中国移动在线服务有限公司": "China",
        "云集": "China",
        "互联网大厂": "China",
        "兆艺智慧城市": "China",
        "兴盛优选": "China",
        "北京顺丰同城科技有限公司": "China",
        "华南理工大学": "China",
        "咪咕视讯": "China",
        "哈尔冰工业大学": "China",
        "多奇數位創意有限公司": "China",
        "天津津门地界有限公司": "China",
        "如梦技术": "China",
        "宝付网络科技(上海)有限公司": "China",
        "快手": "China",
        "扫码关注": "China",
        "拼多多": "China",
        "掌门一对一": "China",
        "新供给科技": "China",
        "无": "China",
        "武汉猫头鹰团队成员": "China",
        "水滴互助": "China",
        "江苏众享金联": "China",
        "浙江蕙康科技有限公司": "China",
        "浙江非线数联": "China",
        "涂鸦": "China",
        "爱因互动": "China",
        "维沃移动通信": "China",
        "网易云音乐 apache": "USA",
        "美团": "China",
        "腾讯": "China",
        "艾耕科技": "China",
        "芋道源码，纯源码解析公众号": "China",
        "蚂蚁金服": "China",
        "运满满": "China",
        "韩都衣舍": "China",
        "魔界天使": "China"
    }

