--pytorch maintainer总体贡献
--pytorch maintainer 2级目录贡献
--pytorch  maintainer 3级目录贡献
--maintainer issues 发起次数
-- maintainer issue 回复或评论次数
-- maintainer总体贡献
--maintainer pr approved 次数
select search_key__owner,
       search_key__repo,
       toYYYYMM(authored_date) as commit_month,
       b.author__login,
       count()                 as commit_count
from (select * from gits where search_key__owner = 'pytorch' and if_merged = 0) as a global
         join (select *
               from (select commit__author__email, author__login
                     from github_commits
                     where author__id != 0
                     group by commit__author__email, author__login)
               where author__login global in (select a as maintainer_login
                                              from (select ['soumith',
                                                               'soumith',
                                                               'ezyang',
                                                               'gchanan',
                                                               'dzhulgakov',
                                                               'gchanan',
                                                               'soumith',
                                                               'jbschlosser',
                                                               'albanD',
                                                               'colesbury',
                                                               'apaszke',
                                                               'albanD',
                                                               'jbschlosser',
                                                               'soumith',
                                                               'iramazanli',
                                                               'vincentqb',
                                                               'ezyang',
                                                               'alband',
                                                               'soulitzer',
                                                               'apaszke',
                                                               'eellison',
                                                               'suo',
                                                               'gmagogsfm',
                                                               'jamesr66a',
                                                               'jansel',
                                                               'zdevito',
                                                               'fritzo',
                                                               'neerajprad',
                                                               'alicanb',
                                                               'vishwakftw',
                                                               'mrshenli',
                                                               'pritamdamania87',
                                                               'zhaojuanmao',
                                                               'rohan-varma',
                                                               'wanchaol',
                                                               'fduwjj',
                                                               'H-Huang',
                                                               'd4l3k',
                                                               'aazzolini',
                                                               'kwen2501',
                                                               'jamesr66a',
                                                               'kiukchung',
                                                               'pietern',
                                                               'mingzhe09088',
                                                               'osalpekar',
                                                               'VitalyFedyunin',
                                                               'SsnL',
                                                               'apaszke',
                                                               'mruberry',
                                                               'Lezcano',
                                                               'IvanYashchuk',
                                                               'vishwakftw',
                                                               'pearu',
                                                               'nikitaved',
                                                               'IvanYashchuk',
                                                               'cpuhrsch',
                                                               'mruberry',
                                                               'peterbell10',
                                                               'VitalyFedyunin',
                                                               'mingfeima',
                                                               'zheng-xq',
                                                               'colesbury',
                                                               'cpuhrsch',
                                                               'ilia-cher',
                                                               'ngimel',
                                                               'ezyang',
                                                               'ptrblck',
                                                               'csarofeen',
                                                               'ajtulloch',
                                                               'zheng-xq',
                                                               'csarofeen',
                                                               'jjsjann123',
                                                               'ptrblck',
                                                               'ngimel',
                                                               'VitalyFedyunin',
                                                               'Jianhui-Li',
                                                               'mingfeima',
                                                               'bddppq',
                                                               'yinghai',
                                                               'sunway513',
                                                               'jithunnair-amd',
                                                               'jeffdaily',
                                                               'bddppq',
                                                               'malfet',
                                                               'seemethere',
                                                               'alband',
                                                               'dagitses',
                                                               'osalpekar',
                                                               'ZainRizvi',
                                                               'mehtanirav',
                                                               'atalman',
                                                               'zhouzhuojie',
                                                               'ezyang',
                                                               'kostmo',
                                                               'adnanaziz',
                                                               'ckluk',
                                                               'robieta',
                                                               'xuzhao9',
                                                               'chauhang',
                                                               'bitfort',
                                                               'gdankel',
                                                               'ngimel',
                                                               'mingzhe09088',
                                                               'jbschlosser',
                                                               'yf225',
                                                               'bdhirsh',
                                                               'ezyang',
                                                               'dzhulgakov',
                                                               'smessmer',
                                                               'BowenBao',
                                                               'abock',
                                                               'garymm',
                                                               'lara-hdr',
                                                               'houseroad',
                                                               'neginraoof',
                                                               'spandantiwari',
                                                               'dreiss',
                                                               'raziel',
                                                               'linbinyu',
                                                               'IvanKobzarev',
                                                               'xta0',
                                                               'raghuramank100',
                                                               'jerryzh168',
                                                               'z-a-f',
                                                               'supriyar',
                                                               'nbcsm',
                                                               'gaoteng-git',
                                                               'peterjc123',
                                                               'alband',
                                                               'malfet',
                                                               'kulinseth',
                                                               'razarmehr',
                                                               'avmgithub',
                                                               'svekars',
                                                               'JackCaoG',
                                                               'jysohn23',
                                                               'zcain117',
                                                               'bdhirsh',
                                                               'gchanan',
                                                               'ailzhang',
                                                               'dlibenzi',
                                                               'asuhan',
                                                               'chauhang',
                                                               'mycpuorg',
                                                               'vdantu',
                                                               'dhanainme',
                                                               'fmassa',
                                                               'datumbox',
                                                               'parmeet',
                                                               'hudeven',
                                                               'zhangguanheng66',
                                                               'cpuhrsch',
                                                               'mthrok',
                                                               'vincentqb',
                                                               'divchenko',
                                                               'colin2328',
                                                               'd4l3k',
                                                               'kiukchung',
                                                               'VitalyFedyunin',
                                                               'wenleix'] as a)
                                                       array join a
                                              group by a)) as b on a.author_email = b.commit__author__email
group by search_key__owner, search_key__repo, author__login, commit_month
order by search_key__owner, search_key__repo, commit_count desc, author__login, commit_month;


-- maintainer 2级目录贡献
select search_key__owner,
       search_key__repo,
       in_dir,
       author__login,
       toYYYYMM(authored_date) as alter_file_month,
       count()                    alter_file_count
from (select * from gits_dir_label where search_key__owner = 'pytorch') as a global
         join (select *
               from (select commit__author__email, author__login
                     from github_commits
                     where author__id != 0
                     group by commit__author__email, author__login)
               where author__login global in (select a as maintainer_login
                                              from (select ['soumith',
                                                               'soumith',
                                                               'ezyang',
                                                               'gchanan',
                                                               'dzhulgakov',
                                                               'gchanan',
                                                               'soumith',
                                                               'jbschlosser',
                                                               'albanD',
                                                               'colesbury',
                                                               'apaszke',
                                                               'albanD',
                                                               'jbschlosser',
                                                               'soumith',
                                                               'iramazanli',
                                                               'vincentqb',
                                                               'ezyang',
                                                               'alband',
                                                               'soulitzer',
                                                               'apaszke',
                                                               'eellison',
                                                               'suo',
                                                               'gmagogsfm',
                                                               'jamesr66a',
                                                               'jansel',
                                                               'zdevito',
                                                               'fritzo',
                                                               'neerajprad',
                                                               'alicanb',
                                                               'vishwakftw',
                                                               'mrshenli',
                                                               'pritamdamania87',
                                                               'zhaojuanmao',
                                                               'rohan-varma',
                                                               'wanchaol',
                                                               'fduwjj',
                                                               'H-Huang',
                                                               'd4l3k',
                                                               'aazzolini',
                                                               'kwen2501',
                                                               'jamesr66a',
                                                               'kiukchung',
                                                               'pietern',
                                                               'mingzhe09088',
                                                               'osalpekar',
                                                               'VitalyFedyunin',
                                                               'SsnL',
                                                               'apaszke',
                                                               'mruberry',
                                                               'Lezcano',
                                                               'IvanYashchuk',
                                                               'vishwakftw',
                                                               'pearu',
                                                               'nikitaved',
                                                               'IvanYashchuk',
                                                               'cpuhrsch',
                                                               'mruberry',
                                                               'peterbell10',
                                                               'VitalyFedyunin',
                                                               'mingfeima',
                                                               'zheng-xq',
                                                               'colesbury',
                                                               'cpuhrsch',
                                                               'ilia-cher',
                                                               'ngimel',
                                                               'ezyang',
                                                               'ptrblck',
                                                               'csarofeen',
                                                               'ajtulloch',
                                                               'zheng-xq',
                                                               'csarofeen',
                                                               'jjsjann123',
                                                               'ptrblck',
                                                               'ngimel',
                                                               'VitalyFedyunin',
                                                               'Jianhui-Li',
                                                               'mingfeima',
                                                               'bddppq',
                                                               'yinghai',
                                                               'sunway513',
                                                               'jithunnair-amd',
                                                               'jeffdaily',
                                                               'bddppq',
                                                               'malfet',
                                                               'seemethere',
                                                               'alband',
                                                               'dagitses',
                                                               'osalpekar',
                                                               'ZainRizvi',
                                                               'mehtanirav',
                                                               'atalman',
                                                               'zhouzhuojie',
                                                               'ezyang',
                                                               'kostmo',
                                                               'adnanaziz',
                                                               'ckluk',
                                                               'robieta',
                                                               'xuzhao9',
                                                               'chauhang',
                                                               'bitfort',
                                                               'gdankel',
                                                               'ngimel',
                                                               'mingzhe09088',
                                                               'jbschlosser',
                                                               'yf225',
                                                               'bdhirsh',
                                                               'ezyang',
                                                               'dzhulgakov',
                                                               'smessmer',
                                                               'BowenBao',
                                                               'abock',
                                                               'garymm',
                                                               'lara-hdr',
                                                               'houseroad',
                                                               'neginraoof',
                                                               'spandantiwari',
                                                               'dreiss',
                                                               'raziel',
                                                               'linbinyu',
                                                               'IvanKobzarev',
                                                               'xta0',
                                                               'raghuramank100',
                                                               'jerryzh168',
                                                               'z-a-f',
                                                               'supriyar',
                                                               'nbcsm',
                                                               'gaoteng-git',
                                                               'peterjc123',
                                                               'alband',
                                                               'malfet',
                                                               'kulinseth',
                                                               'razarmehr',
                                                               'avmgithub',
                                                               'svekars',
                                                               'JackCaoG',
                                                               'jysohn23',
                                                               'zcain117',
                                                               'bdhirsh',
                                                               'gchanan',
                                                               'ailzhang',
                                                               'dlibenzi',
                                                               'asuhan',
                                                               'chauhang',
                                                               'mycpuorg',
                                                               'vdantu',
                                                               'dhanainme',
                                                               'fmassa',
                                                               'datumbox',
                                                               'parmeet',
                                                               'hudeven',
                                                               'zhangguanheng66',
                                                               'cpuhrsch',
                                                               'mthrok',
                                                               'vincentqb',
                                                               'divchenko',
                                                               'colin2328',
                                                               'd4l3k',
                                                               'kiukchung',
                                                               'VitalyFedyunin',
                                                               'wenleix'] as a)
                                                       array join a
                                              group by a)) as b on a.author_email = b.commit__author__email
where length(splitByChar('/', in_dir)) = 3
group by search_key__owner, search_key__repo, toYYYYMM(authored_date), author__login, in_dir
order by search_key__owner, search_key__repo, in_dir, alter_file_count desc, author__login, alter_file_month;

-- maintainer 3级目录贡献
select search_key__owner,
       search_key__repo,
       in_dir,
       author__login,
       toYYYYMM(authored_date) as alter_file_month,
       count()                    alter_file_count
from (select * from gits_dir_label where search_key__owner = 'pytorch') as a global
         join (select *
               from (select commit__author__email, author__login
                     from github_commits
                     where author__id != 0
                     group by commit__author__email, author__login)
               where author__login global in (select a as maintainer_login
                                              from (select ['soumith',
                                                               'soumith',
                                                               'ezyang',
                                                               'gchanan',
                                                               'dzhulgakov',
                                                               'gchanan',
                                                               'soumith',
                                                               'jbschlosser',
                                                               'albanD',
                                                               'colesbury',
                                                               'apaszke',
                                                               'albanD',
                                                               'jbschlosser',
                                                               'soumith',
                                                               'iramazanli',
                                                               'vincentqb',
                                                               'ezyang',
                                                               'alband',
                                                               'soulitzer',
                                                               'apaszke',
                                                               'eellison',
                                                               'suo',
                                                               'gmagogsfm',
                                                               'jamesr66a',
                                                               'jansel',
                                                               'zdevito',
                                                               'fritzo',
                                                               'neerajprad',
                                                               'alicanb',
                                                               'vishwakftw',
                                                               'mrshenli',
                                                               'pritamdamania87',
                                                               'zhaojuanmao',
                                                               'rohan-varma',
                                                               'wanchaol',
                                                               'fduwjj',
                                                               'H-Huang',
                                                               'd4l3k',
                                                               'aazzolini',
                                                               'kwen2501',
                                                               'jamesr66a',
                                                               'kiukchung',
                                                               'pietern',
                                                               'mingzhe09088',
                                                               'osalpekar',
                                                               'VitalyFedyunin',
                                                               'SsnL',
                                                               'apaszke',
                                                               'mruberry',
                                                               'Lezcano',
                                                               'IvanYashchuk',
                                                               'vishwakftw',
                                                               'pearu',
                                                               'nikitaved',
                                                               'IvanYashchuk',
                                                               'cpuhrsch',
                                                               'mruberry',
                                                               'peterbell10',
                                                               'VitalyFedyunin',
                                                               'mingfeima',
                                                               'zheng-xq',
                                                               'colesbury',
                                                               'cpuhrsch',
                                                               'ilia-cher',
                                                               'ngimel',
                                                               'ezyang',
                                                               'ptrblck',
                                                               'csarofeen',
                                                               'ajtulloch',
                                                               'zheng-xq',
                                                               'csarofeen',
                                                               'jjsjann123',
                                                               'ptrblck',
                                                               'ngimel',
                                                               'VitalyFedyunin',
                                                               'Jianhui-Li',
                                                               'mingfeima',
                                                               'bddppq',
                                                               'yinghai',
                                                               'sunway513',
                                                               'jithunnair-amd',
                                                               'jeffdaily',
                                                               'bddppq',
                                                               'malfet',
                                                               'seemethere',
                                                               'alband',
                                                               'dagitses',
                                                               'osalpekar',
                                                               'ZainRizvi',
                                                               'mehtanirav',
                                                               'atalman',
                                                               'zhouzhuojie',
                                                               'ezyang',
                                                               'kostmo',
                                                               'adnanaziz',
                                                               'ckluk',
                                                               'robieta',
                                                               'xuzhao9',
                                                               'chauhang',
                                                               'bitfort',
                                                               'gdankel',
                                                               'ngimel',
                                                               'mingzhe09088',
                                                               'jbschlosser',
                                                               'yf225',
                                                               'bdhirsh',
                                                               'ezyang',
                                                               'dzhulgakov',
                                                               'smessmer',
                                                               'BowenBao',
                                                               'abock',
                                                               'garymm',
                                                               'lara-hdr',
                                                               'houseroad',
                                                               'neginraoof',
                                                               'spandantiwari',
                                                               'dreiss',
                                                               'raziel',
                                                               'linbinyu',
                                                               'IvanKobzarev',
                                                               'xta0',
                                                               'raghuramank100',
                                                               'jerryzh168',
                                                               'z-a-f',
                                                               'supriyar',
                                                               'nbcsm',
                                                               'gaoteng-git',
                                                               'peterjc123',
                                                               'alband',
                                                               'malfet',
                                                               'kulinseth',
                                                               'razarmehr',
                                                               'avmgithub',
                                                               'svekars',
                                                               'JackCaoG',
                                                               'jysohn23',
                                                               'zcain117',
                                                               'bdhirsh',
                                                               'gchanan',
                                                               'ailzhang',
                                                               'dlibenzi',
                                                               'asuhan',
                                                               'chauhang',
                                                               'mycpuorg',
                                                               'vdantu',
                                                               'dhanainme',
                                                               'fmassa',
                                                               'datumbox',
                                                               'parmeet',
                                                               'hudeven',
                                                               'zhangguanheng66',
                                                               'cpuhrsch',
                                                               'mthrok',
                                                               'vincentqb',
                                                               'divchenko',
                                                               'colin2328',
                                                               'd4l3k',
                                                               'kiukchung',
                                                               'VitalyFedyunin',
                                                               'wenleix'] as a)
                                                       array join a
                                              group by a)) as b on a.author_email = b.commit__author__email
where length(splitByChar('/', in_dir)) = 4
group by search_key__owner, search_key__repo, toYYYYMM(authored_date), author__login, in_dir
order by search_key__owner, search_key__repo, in_dir, alter_file_count desc, author__login, alter_file_month;


--maintainer issues 发起次数
select search_key__owner,
       search_key__repo,
       user__login,
       toYYYYMM(created_at) as create_issues_month,
       count()                 create_issue_count
from github_issues
where search_key__owner = 'pytorch'
  and user__login global in (select a as maintainer_login
                             from (select ['soumith',
                                              'soumith',
                                              'ezyang',
                                              'gchanan',
                                              'dzhulgakov',
                                              'gchanan',
                                              'soumith',
                                              'jbschlosser',
                                              'albanD',
                                              'colesbury',
                                              'apaszke',
                                              'albanD',
                                              'jbschlosser',
                                              'soumith',
                                              'iramazanli',
                                              'vincentqb',
                                              'ezyang',
                                              'alband',
                                              'soulitzer',
                                              'apaszke',
                                              'eellison',
                                              'suo',
                                              'gmagogsfm',
                                              'jamesr66a',
                                              'jansel',
                                              'zdevito',
                                              'fritzo',
                                              'neerajprad',
                                              'alicanb',
                                              'vishwakftw',
                                              'mrshenli',
                                              'pritamdamania87',
                                              'zhaojuanmao',
                                              'rohan-varma',
                                              'wanchaol',
                                              'fduwjj',
                                              'H-Huang',
                                              'd4l3k',
                                              'aazzolini',
                                              'kwen2501',
                                              'jamesr66a',
                                              'kiukchung',
                                              'pietern',
                                              'mingzhe09088',
                                              'osalpekar',
                                              'VitalyFedyunin',
                                              'SsnL',
                                              'apaszke',
                                              'mruberry',
                                              'Lezcano',
                                              'IvanYashchuk',
                                              'vishwakftw',
                                              'pearu',
                                              'nikitaved',
                                              'IvanYashchuk',
                                              'cpuhrsch',
                                              'mruberry',
                                              'peterbell10',
                                              'VitalyFedyunin',
                                              'mingfeima',
                                              'zheng-xq',
                                              'colesbury',
                                              'cpuhrsch',
                                              'ilia-cher',
                                              'ngimel',
                                              'ezyang',
                                              'ptrblck',
                                              'csarofeen',
                                              'ajtulloch',
                                              'zheng-xq',
                                              'csarofeen',
                                              'jjsjann123',
                                              'ptrblck',
                                              'ngimel',
                                              'VitalyFedyunin',
                                              'Jianhui-Li',
                                              'mingfeima',
                                              'bddppq',
                                              'yinghai',
                                              'sunway513',
                                              'jithunnair-amd',
                                              'jeffdaily',
                                              'bddppq',
                                              'malfet',
                                              'seemethere',
                                              'alband',
                                              'dagitses',
                                              'osalpekar',
                                              'ZainRizvi',
                                              'mehtanirav',
                                              'atalman',
                                              'zhouzhuojie',
                                              'ezyang',
                                              'kostmo',
                                              'adnanaziz',
                                              'ckluk',
                                              'robieta',
                                              'xuzhao9',
                                              'chauhang',
                                              'bitfort',
                                              'gdankel',
                                              'ngimel',
                                              'mingzhe09088',
                                              'jbschlosser',
                                              'yf225',
                                              'bdhirsh',
                                              'ezyang',
                                              'dzhulgakov',
                                              'smessmer',
                                              'BowenBao',
                                              'abock',
                                              'garymm',
                                              'lara-hdr',
                                              'houseroad',
                                              'neginraoof',
                                              'spandantiwari',
                                              'dreiss',
                                              'raziel',
                                              'linbinyu',
                                              'IvanKobzarev',
                                              'xta0',
                                              'raghuramank100',
                                              'jerryzh168',
                                              'z-a-f',
                                              'supriyar',
                                              'nbcsm',
                                              'gaoteng-git',
                                              'peterjc123',
                                              'alband',
                                              'malfet',
                                              'kulinseth',
                                              'razarmehr',
                                              'avmgithub',
                                              'svekars',
                                              'JackCaoG',
                                              'jysohn23',
                                              'zcain117',
                                              'bdhirsh',
                                              'gchanan',
                                              'ailzhang',
                                              'dlibenzi',
                                              'asuhan',
                                              'chauhang',
                                              'mycpuorg',
                                              'vdantu',
                                              'dhanainme',
                                              'fmassa',
                                              'datumbox',
                                              'parmeet',
                                              'hudeven',
                                              'zhangguanheng66',
                                              'cpuhrsch',
                                              'mthrok',
                                              'vincentqb',
                                              'divchenko',
                                              'colin2328',
                                              'd4l3k',
                                              'kiukchung',
                                              'VitalyFedyunin',
                                              'wenleix'] as a)
                                      array join a
                             group by a)
  and pull_request__url = ''
group by search_key__owner, search_key__repo, user__login, create_issues_month
order by search_key__owner, search_key__repo, create_issue_count desc, user__login, create_issues_month
;
-- maintainer issue 回复或评论次数
select search_key__owner, search_key__repo, user__login, toYYYYMM(created_at) as reply_at, count() as comments_count
from github_issues_comments a global
         join (select search_key__owner, search_key__repo, number
               from github_issues
               where pull_request__url = ''
               group by search_key__owner, search_key__repo, number) as b
              on a.search_key__owner = b.search_key__owner and a.search_key__repo = b.search_key__repo and
                 a.search_key__number = b.number
where search_key__owner = 'pytorch'
  and user__login global in (select a as maintainer_login
                             from (select ['soumith',
                                              'soumith',
                                              'ezyang',
                                              'gchanan',
                                              'dzhulgakov',
                                              'gchanan',
                                              'soumith',
                                              'jbschlosser',
                                              'albanD',
                                              'colesbury',
                                              'apaszke',
                                              'albanD',
                                              'jbschlosser',
                                              'soumith',
                                              'iramazanli',
                                              'vincentqb',
                                              'ezyang',
                                              'alband',
                                              'soulitzer',
                                              'apaszke',
                                              'eellison',
                                              'suo',
                                              'gmagogsfm',
                                              'jamesr66a',
                                              'jansel',
                                              'zdevito',
                                              'fritzo',
                                              'neerajprad',
                                              'alicanb',
                                              'vishwakftw',
                                              'mrshenli',
                                              'pritamdamania87',
                                              'zhaojuanmao',
                                              'rohan-varma',
                                              'wanchaol',
                                              'fduwjj',
                                              'H-Huang',
                                              'd4l3k',
                                              'aazzolini',
                                              'kwen2501',
                                              'jamesr66a',
                                              'kiukchung',
                                              'pietern',
                                              'mingzhe09088',
                                              'osalpekar',
                                              'VitalyFedyunin',
                                              'SsnL',
                                              'apaszke',
                                              'mruberry',
                                              'Lezcano',
                                              'IvanYashchuk',
                                              'vishwakftw',
                                              'pearu',
                                              'nikitaved',
                                              'IvanYashchuk',
                                              'cpuhrsch',
                                              'mruberry',
                                              'peterbell10',
                                              'VitalyFedyunin',
                                              'mingfeima',
                                              'zheng-xq',
                                              'colesbury',
                                              'cpuhrsch',
                                              'ilia-cher',
                                              'ngimel',
                                              'ezyang',
                                              'ptrblck',
                                              'csarofeen',
                                              'ajtulloch',
                                              'zheng-xq',
                                              'csarofeen',
                                              'jjsjann123',
                                              'ptrblck',
                                              'ngimel',
                                              'VitalyFedyunin',
                                              'Jianhui-Li',
                                              'mingfeima',
                                              'bddppq',
                                              'yinghai',
                                              'sunway513',
                                              'jithunnair-amd',
                                              'jeffdaily',
                                              'bddppq',
                                              'malfet',
                                              'seemethere',
                                              'alband',
                                              'dagitses',
                                              'osalpekar',
                                              'ZainRizvi',
                                              'mehtanirav',
                                              'atalman',
                                              'zhouzhuojie',
                                              'ezyang',
                                              'kostmo',
                                              'adnanaziz',
                                              'ckluk',
                                              'robieta',
                                              'xuzhao9',
                                              'chauhang',
                                              'bitfort',
                                              'gdankel',
                                              'ngimel',
                                              'mingzhe09088',
                                              'jbschlosser',
                                              'yf225',
                                              'bdhirsh',
                                              'ezyang',
                                              'dzhulgakov',
                                              'smessmer',
                                              'BowenBao',
                                              'abock',
                                              'garymm',
                                              'lara-hdr',
                                              'houseroad',
                                              'neginraoof',
                                              'spandantiwari',
                                              'dreiss',
                                              'raziel',
                                              'linbinyu',
                                              'IvanKobzarev',
                                              'xta0',
                                              'raghuramank100',
                                              'jerryzh168',
                                              'z-a-f',
                                              'supriyar',
                                              'nbcsm',
                                              'gaoteng-git',
                                              'peterjc123',
                                              'alband',
                                              'malfet',
                                              'kulinseth',
                                              'razarmehr',
                                              'avmgithub',
                                              'svekars',
                                              'JackCaoG',
                                              'jysohn23',
                                              'zcain117',
                                              'bdhirsh',
                                              'gchanan',
                                              'ailzhang',
                                              'dlibenzi',
                                              'asuhan',
                                              'chauhang',
                                              'mycpuorg',
                                              'vdantu',
                                              'dhanainme',
                                              'fmassa',
                                              'datumbox',
                                              'parmeet',
                                              'hudeven',
                                              'zhangguanheng66',
                                              'cpuhrsch',
                                              'mthrok',
                                              'vincentqb',
                                              'divchenko',
                                              'colin2328',
                                              'd4l3k',
                                              'kiukchung',
                                              'VitalyFedyunin',
                                              'wenleix'] as a)
                                      array join a
                             group by a)
group by search_key__owner, search_key__repo, user__login, reply_at
order by search_key__owner, search_key__repo, comments_count desc, user__login, reply_at;


--maintainer pr 发起次数
select search_key__owner,
       search_key__repo,
       user__login,
       toYYYYMM(created_at) as create_issues_month,
       count()                 create_issue_count
from github_pull_requests
where search_key__owner = 'pytorch'
  and user__login global in (select a as maintainer_login
                             from (select ['soumith',
                                              'soumith',
                                              'ezyang',
                                              'gchanan',
                                              'dzhulgakov',
                                              'gchanan',
                                              'soumith',
                                              'jbschlosser',
                                              'albanD',
                                              'colesbury',
                                              'apaszke',
                                              'albanD',
                                              'jbschlosser',
                                              'soumith',
                                              'iramazanli',
                                              'vincentqb',
                                              'ezyang',
                                              'alband',
                                              'soulitzer',
                                              'apaszke',
                                              'eellison',
                                              'suo',
                                              'gmagogsfm',
                                              'jamesr66a',
                                              'jansel',
                                              'zdevito',
                                              'fritzo',
                                              'neerajprad',
                                              'alicanb',
                                              'vishwakftw',
                                              'mrshenli',
                                              'pritamdamania87',
                                              'zhaojuanmao',
                                              'rohan-varma',
                                              'wanchaol',
                                              'fduwjj',
                                              'H-Huang',
                                              'd4l3k',
                                              'aazzolini',
                                              'kwen2501',
                                              'jamesr66a',
                                              'kiukchung',
                                              'pietern',
                                              'mingzhe09088',
                                              'osalpekar',
                                              'VitalyFedyunin',
                                              'SsnL',
                                              'apaszke',
                                              'mruberry',
                                              'Lezcano',
                                              'IvanYashchuk',
                                              'vishwakftw',
                                              'pearu',
                                              'nikitaved',
                                              'IvanYashchuk',
                                              'cpuhrsch',
                                              'mruberry',
                                              'peterbell10',
                                              'VitalyFedyunin',
                                              'mingfeima',
                                              'zheng-xq',
                                              'colesbury',
                                              'cpuhrsch',
                                              'ilia-cher',
                                              'ngimel',
                                              'ezyang',
                                              'ptrblck',
                                              'csarofeen',
                                              'ajtulloch',
                                              'zheng-xq',
                                              'csarofeen',
                                              'jjsjann123',
                                              'ptrblck',
                                              'ngimel',
                                              'VitalyFedyunin',
                                              'Jianhui-Li',
                                              'mingfeima',
                                              'bddppq',
                                              'yinghai',
                                              'sunway513',
                                              'jithunnair-amd',
                                              'jeffdaily',
                                              'bddppq',
                                              'malfet',
                                              'seemethere',
                                              'alband',
                                              'dagitses',
                                              'osalpekar',
                                              'ZainRizvi',
                                              'mehtanirav',
                                              'atalman',
                                              'zhouzhuojie',
                                              'ezyang',
                                              'kostmo',
                                              'adnanaziz',
                                              'ckluk',
                                              'robieta',
                                              'xuzhao9',
                                              'chauhang',
                                              'bitfort',
                                              'gdankel',
                                              'ngimel',
                                              'mingzhe09088',
                                              'jbschlosser',
                                              'yf225',
                                              'bdhirsh',
                                              'ezyang',
                                              'dzhulgakov',
                                              'smessmer',
                                              'BowenBao',
                                              'abock',
                                              'garymm',
                                              'lara-hdr',
                                              'houseroad',
                                              'neginraoof',
                                              'spandantiwari',
                                              'dreiss',
                                              'raziel',
                                              'linbinyu',
                                              'IvanKobzarev',
                                              'xta0',
                                              'raghuramank100',
                                              'jerryzh168',
                                              'z-a-f',
                                              'supriyar',
                                              'nbcsm',
                                              'gaoteng-git',
                                              'peterjc123',
                                              'alband',
                                              'malfet',
                                              'kulinseth',
                                              'razarmehr',
                                              'avmgithub',
                                              'svekars',
                                              'JackCaoG',
                                              'jysohn23',
                                              'zcain117',
                                              'bdhirsh',
                                              'gchanan',
                                              'ailzhang',
                                              'dlibenzi',
                                              'asuhan',
                                              'chauhang',
                                              'mycpuorg',
                                              'vdantu',
                                              'dhanainme',
                                              'fmassa',
                                              'datumbox',
                                              'parmeet',
                                              'hudeven',
                                              'zhangguanheng66',
                                              'cpuhrsch',
                                              'mthrok',
                                              'vincentqb',
                                              'divchenko',
                                              'colin2328',
                                              'd4l3k',
                                              'kiukchung',
                                              'VitalyFedyunin',
                                              'wenleix'] as a)
                                      array join a
                             group by a)
group by search_key__owner, search_key__repo, user__login, create_issues_month
order by search_key__owner, search_key__repo, create_issue_count desc, user__login, create_issues_month;


-- maintainer pr回复次数
select search_key__owner,
       search_key__repo,
       login,
       toYYYYMM(toDateTime(splitByChar('T', submitted_at)[1])) as reply_at,
       count()                                                    reply_count
from (select a.search_key__owner,
             a.search_key__repo,
             search_key__event,
             search_key__number,
             JSONExtractString(timeline_raw, 'submitted_at')                     as submitted_at,
             JSONExtractString(JSONExtractString(timeline_raw, 'user'), 'login') as login
      from (select *
            from github_issues_timeline
            where search_key__owner = 'pytorch'
              and search_key__event = 'reviewed') as a global
               join (select search_key__owner, search_key__repo, number
                     from github_pull_requests
                     where search_key__owner = 'pytorch'
                     group by search_key__owner, search_key__repo, number) as b
                    on a.search_key__owner = b.search_key__owner and a.search_key__repo = b.search_key__repo and
                       a.search_key__number = b.number)
where login global in (select a as maintainer_login
                       from (select ['soumith',
                                        'soumith',
                                        'ezyang',
                                        'gchanan',
                                        'dzhulgakov',
                                        'gchanan',
                                        'soumith',
                                        'jbschlosser',
                                        'albanD',
                                        'colesbury',
                                        'apaszke',
                                        'albanD',
                                        'jbschlosser',
                                        'soumith',
                                        'iramazanli',
                                        'vincentqb',
                                        'ezyang',
                                        'alband',
                                        'soulitzer',
                                        'apaszke',
                                        'eellison',
                                        'suo',
                                        'gmagogsfm',
                                        'jamesr66a',
                                        'jansel',
                                        'zdevito',
                                        'fritzo',
                                        'neerajprad',
                                        'alicanb',
                                        'vishwakftw',
                                        'mrshenli',
                                        'pritamdamania87',
                                        'zhaojuanmao',
                                        'rohan-varma',
                                        'wanchaol',
                                        'fduwjj',
                                        'H-Huang',
                                        'd4l3k',
                                        'aazzolini',
                                        'kwen2501',
                                        'jamesr66a',
                                        'kiukchung',
                                        'pietern',
                                        'mingzhe09088',
                                        'osalpekar',
                                        'VitalyFedyunin',
                                        'SsnL',
                                        'apaszke',
                                        'mruberry',
                                        'Lezcano',
                                        'IvanYashchuk',
                                        'vishwakftw',
                                        'pearu',
                                        'nikitaved',
                                        'IvanYashchuk',
                                        'cpuhrsch',
                                        'mruberry',
                                        'peterbell10',
                                        'VitalyFedyunin',
                                        'mingfeima',
                                        'zheng-xq',
                                        'colesbury',
                                        'cpuhrsch',
                                        'ilia-cher',
                                        'ngimel',
                                        'ezyang',
                                        'ptrblck',
                                        'csarofeen',
                                        'ajtulloch',
                                        'zheng-xq',
                                        'csarofeen',
                                        'jjsjann123',
                                        'ptrblck',
                                        'ngimel',
                                        'VitalyFedyunin',
                                        'Jianhui-Li',
                                        'mingfeima',
                                        'bddppq',
                                        'yinghai',
                                        'sunway513',
                                        'jithunnair-amd',
                                        'jeffdaily',
                                        'bddppq',
                                        'malfet',
                                        'seemethere',
                                        'alband',
                                        'dagitses',
                                        'osalpekar',
                                        'ZainRizvi',
                                        'mehtanirav',
                                        'atalman',
                                        'zhouzhuojie',
                                        'ezyang',
                                        'kostmo',
                                        'adnanaziz',
                                        'ckluk',
                                        'robieta',
                                        'xuzhao9',
                                        'chauhang',
                                        'bitfort',
                                        'gdankel',
                                        'ngimel',
                                        'mingzhe09088',
                                        'jbschlosser',
                                        'yf225',
                                        'bdhirsh',
                                        'ezyang',
                                        'dzhulgakov',
                                        'smessmer',
                                        'BowenBao',
                                        'abock',
                                        'garymm',
                                        'lara-hdr',
                                        'houseroad',
                                        'neginraoof',
                                        'spandantiwari',
                                        'dreiss',
                                        'raziel',
                                        'linbinyu',
                                        'IvanKobzarev',
                                        'xta0',
                                        'raghuramank100',
                                        'jerryzh168',
                                        'z-a-f',
                                        'supriyar',
                                        'nbcsm',
                                        'gaoteng-git',
                                        'peterjc123',
                                        'alband',
                                        'malfet',
                                        'kulinseth',
                                        'razarmehr',
                                        'avmgithub',
                                        'svekars',
                                        'JackCaoG',
                                        'jysohn23',
                                        'zcain117',
                                        'bdhirsh',
                                        'gchanan',
                                        'ailzhang',
                                        'dlibenzi',
                                        'asuhan',
                                        'chauhang',
                                        'mycpuorg',
                                        'vdantu',
                                        'dhanainme',
                                        'fmassa',
                                        'datumbox',
                                        'parmeet',
                                        'hudeven',
                                        'zhangguanheng66',
                                        'cpuhrsch',
                                        'mthrok',
                                        'vincentqb',
                                        'divchenko',
                                        'colin2328',
                                        'd4l3k',
                                        'kiukchung',
                                        'VitalyFedyunin',
                                        'wenleix'] as a)
                                array join a
                       group by a)
group by search_key__owner, search_key__repo, login, reply_at
order by search_key__owner, search_key__repo, login, reply_count desc, reply_count;


--maintainer pr approved 次数
select search_key__owner,
       search_key__repo,
       login,
       toYYYYMM(toDateTime(splitByChar('T', submitted_at)[1])) as reply_at,
       count()                                                    reply_count
from (select a.search_key__owner,
             a.search_key__repo,
             search_key__event,
             search_key__number,
             JSONExtractString(timeline_raw, 'submitted_at')                     as submitted_at,
             JSONExtractString(JSONExtractString(timeline_raw, 'user'), 'login') as login
      from (select *
            from github_issues_timeline
            where search_key__owner = 'pytorch'
              and search_key__event = 'reviewed'
              and JSONExtractString(timeline_raw, 'state') = 'approved') as a global
               join (select search_key__owner, search_key__repo, number
                     from github_pull_requests
                     where search_key__owner = 'pytorch'
                     group by search_key__owner, search_key__repo, number) as b
                    on a.search_key__owner = b.search_key__owner and a.search_key__repo = b.search_key__repo and
                       a.search_key__number = b.number)
where login global in (select a as maintainer_login
                       from (select ['soumith',
                                        'soumith',
                                        'ezyang',
                                        'gchanan',
                                        'dzhulgakov',
                                        'gchanan',
                                        'soumith',
                                        'jbschlosser',
                                        'albanD',
                                        'colesbury',
                                        'apaszke',
                                        'albanD',
                                        'jbschlosser',
                                        'soumith',
                                        'iramazanli',
                                        'vincentqb',
                                        'ezyang',
                                        'alband',
                                        'soulitzer',
                                        'apaszke',
                                        'eellison',
                                        'suo',
                                        'gmagogsfm',
                                        'jamesr66a',
                                        'jansel',
                                        'zdevito',
                                        'fritzo',
                                        'neerajprad',
                                        'alicanb',
                                        'vishwakftw',
                                        'mrshenli',
                                        'pritamdamania87',
                                        'zhaojuanmao',
                                        'rohan-varma',
                                        'wanchaol',
                                        'fduwjj',
                                        'H-Huang',
                                        'd4l3k',
                                        'aazzolini',
                                        'kwen2501',
                                        'jamesr66a',
                                        'kiukchung',
                                        'pietern',
                                        'mingzhe09088',
                                        'osalpekar',
                                        'VitalyFedyunin',
                                        'SsnL',
                                        'apaszke',
                                        'mruberry',
                                        'Lezcano',
                                        'IvanYashchuk',
                                        'vishwakftw',
                                        'pearu',
                                        'nikitaved',
                                        'IvanYashchuk',
                                        'cpuhrsch',
                                        'mruberry',
                                        'peterbell10',
                                        'VitalyFedyunin',
                                        'mingfeima',
                                        'zheng-xq',
                                        'colesbury',
                                        'cpuhrsch',
                                        'ilia-cher',
                                        'ngimel',
                                        'ezyang',
                                        'ptrblck',
                                        'csarofeen',
                                        'ajtulloch',
                                        'zheng-xq',
                                        'csarofeen',
                                        'jjsjann123',
                                        'ptrblck',
                                        'ngimel',
                                        'VitalyFedyunin',
                                        'Jianhui-Li',
                                        'mingfeima',
                                        'bddppq',
                                        'yinghai',
                                        'sunway513',
                                        'jithunnair-amd',
                                        'jeffdaily',
                                        'bddppq',
                                        'malfet',
                                        'seemethere',
                                        'alband',
                                        'dagitses',
                                        'osalpekar',
                                        'ZainRizvi',
                                        'mehtanirav',
                                        'atalman',
                                        'zhouzhuojie',
                                        'ezyang',
                                        'kostmo',
                                        'adnanaziz',
                                        'ckluk',
                                        'robieta',
                                        'xuzhao9',
                                        'chauhang',
                                        'bitfort',
                                        'gdankel',
                                        'ngimel',
                                        'mingzhe09088',
                                        'jbschlosser',
                                        'yf225',
                                        'bdhirsh',
                                        'ezyang',
                                        'dzhulgakov',
                                        'smessmer',
                                        'BowenBao',
                                        'abock',
                                        'garymm',
                                        'lara-hdr',
                                        'houseroad',
                                        'neginraoof',
                                        'spandantiwari',
                                        'dreiss',
                                        'raziel',
                                        'linbinyu',
                                        'IvanKobzarev',
                                        'xta0',
                                        'raghuramank100',
                                        'jerryzh168',
                                        'z-a-f',
                                        'supriyar',
                                        'nbcsm',
                                        'gaoteng-git',
                                        'peterjc123',
                                        'alband',
                                        'malfet',
                                        'kulinseth',
                                        'razarmehr',
                                        'avmgithub',
                                        'svekars',
                                        'JackCaoG',
                                        'jysohn23',
                                        'zcain117',
                                        'bdhirsh',
                                        'gchanan',
                                        'ailzhang',
                                        'dlibenzi',
                                        'asuhan',
                                        'chauhang',
                                        'mycpuorg',
                                        'vdantu',
                                        'dhanainme',
                                        'fmassa',
                                        'datumbox',
                                        'parmeet',
                                        'hudeven',
                                        'zhangguanheng66',
                                        'cpuhrsch',
                                        'mthrok',
                                        'vincentqb',
                                        'divchenko',
                                        'colin2328',
                                        'd4l3k',
                                        'kiukchung',
                                        'VitalyFedyunin',
                                        'wenleix'] as a)
                                array join a
                       group by a)
group by search_key__owner, search_key__repo, login, reply_at
order by search_key__owner, search_key__repo, login, reply_count desc, reply_count;
