{
 "title": "OSS_Know_Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "metrics_owner",
    "label": "metrics_owner",
    "query": "SELECT distinct owner FROM metrics"
   },
   {
    "name": "metrics_repo",
    "label": "metrics_repo",
    "query": "SELECT distinct repo FROM metrics where owner='$metrics_owner'"
   },
   { "name": "github_login", "label": "github_login", "query": "lavalamp" },
   { "name": "git_author_email", "label": "git_author_email", "query": "dbsmith@google.com" },
   {
    "name": "num_contributors",
    "label": "Num of Contributors",
    "query": "SELECT count(distinct github_login) FROM metrics where owner='$metrics_owner' AND repo='$metrics_repo'"
   }
  ]
 },
 "panels": [
  {
   "title": "OSS_Know_Metrics",
   "type": "table",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    github_login,\n    git_author_email,\n    commit_times,\n    changed_lines,\n    diff_file_counts,\n    prs_counts,\n    pr_body_length_avg,\n    issues_counts,\n    issue_body_length_avg,\n    issues_comment_count,\n    issues_comment_body_length_avg,\n    pr_comment_count,\n    pr_comment_body_length_avg,\n    be_mentioned_times_in_issues,\n    be_mentioned_times_in_pr,\n    referred_other_issues_or_prs_in_issue,\n    referred_other_issues_or_prs_in_pr,\n    changed_label_times_in_issues,\n    changed_label_times_in_prs,\n    closed_issues_times,\n    closed_prs_times\nFROM metrics\n\nWHERE\n    owner = '$metrics_owner'\n    AND repo = '$metrics_repo'\nORDER BY issues_counts\n",
     "rawQuery": "SELECT \ngithub_login, git_author_email, commit_times, changed_lines, diff_file_counts, prs_counts, \npr_body_length_avg, issues_counts, issue_body_length_avg, issues_comment_count, \nissues_comment_body_length_avg, pr_comment_count, pr_comment_body_length_avg, \nbe_mentioned_times_in_issues, be_mentioned_times_in_pr, referred_other_issues_or_prs_in_issue, \nreferred_other_issues_or_prs_in_pr, changed_label_times_in_issues, changed_label_times_in_prs, \nclosed_issues_times, closed_prs_times\n\nFROM metrics\n\nWHERE\n    owner = 'torvalds'\n    AND repo = 'linux'\nORDER BY issues_counts",
     "round": "0s"
    }
   ]
  },
  {
   "title": "整体代码提交时区比例",
   "type": "bilibala-echarts-panel",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    author_tz,\n    count(author_tz) as commits_count\nFROM gits\n\nWHERE\n    search_key__owner = '$metrics_owner'\n    and search_key__repo = '$metrics_repo'\nGROUP BY author_tz\nORDER BY commits_count DESC\nLIMIT 5",
     "rawQuery": "SELECT\n    author_tz,\n    count(author_tz) as commits_count\nFROM gits\n\nWHERE\n    search_key__owner = 'kubernetes'\n    and search_key__repo = 'kubernetes'\nGROUP BY author_tz\nORDER BY commits_count DESC\nLIMIT 5",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Developer GitHub Profile",
   "type": "crystaldust-github-profile-panel",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 11 }
  },
  {
   "title": "个人代码提交时区",
   "type": "bilibala-echarts-panel",
   "description": "代码提交时区",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 11 },
   "targets": [
    {
     "database": "default",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    author_tz,\n    count(author_tz) as commits_count\nFROM gits\n\nWHERE\n    search_key__owner = '$metrics_owner'\n    and search_key__repo = '$metrics_repo'\n    and author_email = '$git_author_email'\nGROUP BY author_tz\nORDER BY commits_count DESC\nLIMIT 5",
     "rawQuery": "SELECT\n    author_tz,\n    count(author_tz) as commits_count\nFROM gits\n\nWHERE\n    search_key__owner = 'kubernetes'\n    and search_key__repo = 'kubernetes'\n    and author_email = 'k8s-ci-robot@users.noreply.github.com'\nGROUP BY author_tz\nORDER BY commits_count DESC\nLIMIT 5",
     "round": "0s",
     "table": "gits"
    }
   ]
  },
  {
   "title": "角色雷达图",
   "type": "bilibala-echarts-panel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select owner,\nrepo,\ngithub_id,\ngithub_login,\n\nknowledge_sharing,\ncode_contribution,\nissue_coordination,\nprogress_control,\ncode_tweaking,\nissue_reporting,\n\nmax_knowledge_sharing,\nmin_knowledge_sharing,\n\nmax_code_contribution,\nmin_code_contribution,\n\nmax_issue_coordination,\nmin_issue_coordination,\n\nmax_progress_control,\nmin_progress_control,\n\nmax_code_tweaking,\nmin_code_tweaking,\n\nmax_issue_reporting,\nmin_issue_reporting\nfrom (\n  select *, 1 as jv\n  from activities\n  where owner = '$metrics_owner'\n    and repo = '$metrics_repo'\n    and github_login = '$github_login') as act_info\n  global\n  join (\nselect 1                       as jv,\n    max(knowledge_sharing)  as max_knowledge_sharing,\n    min(knowledge_sharing)  as min_knowledge_sharing,\n    max(code_contribution)  as max_code_contribution,\n    min(code_contribution)  as min_code_contribution,\n    max(issue_coordination) as max_issue_coordination,\n    min(issue_coordination) as min_issue_coordination,\n    max(progress_control)   as max_progress_control,\n    min(progress_control)   as min_progress_control,\n    max(code_tweaking)      as max_code_tweaking,\n    min(code_tweaking)      as min_code_tweaking,\n    max(issue_reporting)    as max_issue_reporting,\n    min(issue_reporting)    as min_issue_reporting\nfrom activities\nwhere owner = '$metrics_owner'\nand repo = '$metrics_repo'\n) as act_jh on act_info.jv = act_jh.jv\n",
     "rawQuery": "select owner,\nrepo,\ngithub_id,\ngithub_login,\n\nknowledge_sharing,\ncode_contribution,\nissue_coordination,\nprogress_control,\ncode_tweaking,\nissue_reporting,\n\nmax_knowledge_sharing,\nmin_knowledge_sharing,\n\nmax_code_contribution,\nmin_code_contribution,\n\nmax_issue_coordination,\nmin_issue_coordination,\n\nmax_progress_control,\nmin_progress_control,\n\nmax_code_tweaking,\nmin_code_tweaking,\n\nmax_issue_reporting,\nmin_issue_reporting\nfrom (\n  select *, 1 as jv\n  from activities\n  where owner = 'GNOME'\n    and repo = 'libxml2'\n    and github_login = 'rickertm') as act_info\n  global\n  join (\nselect 1                       as jv,\n    max(knowledge_sharing)  as max_knowledge_sharing,\n    min(knowledge_sharing)  as min_knowledge_sharing,\n    max(code_contribution)  as max_code_contribution,\n    min(code_contribution)  as min_code_contribution,\n    max(issue_coordination) as max_issue_coordination,\n    min(issue_coordination) as min_issue_coordination,\n    max(progress_control)   as max_progress_control,\n    min(progress_control)   as min_progress_control,\n    max(code_tweaking)      as max_code_tweaking,\n    min(code_tweaking)      as min_code_tweaking,\n    max(issue_reporting)    as max_issue_reporting,\n    min(issue_reporting)    as min_issue_reporting\nfrom activities\nwhere owner = 'GNOME'\nand repo = 'libxml2'\n) as act_jh on act_info.jv = act_jh.jv",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Activities Table",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 19 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    github_login,\n    knowledge_sharing,\n    code_contribution,\n    issue_coordination,\n    progress_control,\n    code_tweaking,\n    issue_reporting\nFROM activities\nWHERE owner='$metrics_owner' AND repo='$metrics_repo'\n",
     "rawQuery": "SELECT\n    github_login,\n    knowledge_sharing,\n    code_contribution,\n    issue_coordination,\n    progress_control,\n    code_tweaking,\n    issue_reporting\nFROM activities\nWHERE owner='google' AND repo='leveldb'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "开发者修改的文件(路径)",
   "type": "table",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 19 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "select author_email,\n       if(length(dir) = 0, '/', concat('/', arrayStringConcat(dir, '/'))) as dir,\n\n       COUNT(files.file_name)                                                file_count,\n       sum(files.lines)                                                      total_lines,\n       sum(files.insertions)                                                 total_insertions,\n       sum(files.deletions)                                                  total_deletions\n\n\nfrom (select search_key__owner,\n             search_key__repo,\n             author_email,\n             `files.insertions`,\n             `files.deletions`,\n             `files.lines`,\n             `files.file_name`,\n             splitByChar('/', `files.file_name`) as f_name,\n             length(f_name)                      as len,\n             arraySlice(f_name, 1, 2)            as dir\n      from gits g\n          array join\n          files.file_name\n         , files.insertions\n         , files.deletions\n         , files.lines\n      WHERE if_merged = 0\n        and search_key__owner = '$metrics_owner'\n        and search_key__repo = '$metrics_repo'\n        and author_email = '$git_author_email'\n        and len > 2)\ngroup by search_key__owner, search_key__repo, author_email, dir\n\n\nUNION ALL\n\nselect author_email,\n       if(length(dir) = 0, '/', concat('/', arrayStringConcat(dir, '/'))) as dir,\n       COUNT(files.file_name)                                                file_count,\n       sum(files.lines)                                                      total_lines,\n       sum(files.insertions)                                                 total_insertions,\n       sum(files.deletions)                                                  total_deletions\nfrom (select search_key__owner,\n             search_key__repo,\n             author_email,\n             `files.insertions`,\n             `files.deletions`,\n             `files.lines`,\n             `files.file_name`,\n             splitByChar('/', `files.file_name`) as f_name,\n             length(f_name)                      as len,\n             arrayPopBack(f_name)                as dir\n      from gits g\n          array join\n          files.file_name\n         , files.insertions\n         , files.deletions\n         , files.lines\n      WHERE if_merged = 0\n        and search_key__owner = '$metrics_owner'\n        and search_key__repo = '$metrics_repo'\n        and author_email = '$git_author_email'\n        and (len = 2 or len = 1))\ngroup by search_key__owner, search_key__repo, author_email, dir",
     "rawQuery": "select author_email,\n       if(length(dir) = 0, '/', concat('/', arrayStringConcat(dir, '/'))) as dir,\n\n       COUNT(files.file_name)                                                file_count,\n       sum(files.lines)                                                      total_lines,\n       sum(files.insertions)                                                 total_insertions,\n       sum(files.deletions)                                                  total_deletions\n\n\nfrom (select search_key__owner,\n             search_key__repo,\n             author_email,\n             `files.insertions`,\n             `files.deletions`,\n             `files.lines`,\n             `files.file_name`,\n             splitByChar('/', `files.file_name`) as f_name,\n             length(f_name)                      as len,\n             arraySlice(f_name, 1, 2)            as dir\n      from gits g\n          array join\n          files.file_name\n         , files.insertions\n         , files.deletions\n         , files.lines\n      WHERE if_merged = 0\n        and search_key__owner = 'google'\n        and search_key__repo = 'leveldb'\n        and author_email = 'cmumford@google.com'\n        and len > 2)\ngroup by search_key__owner, search_key__repo, author_email, dir\n\n\nUNION ALL\n\nselect author_email,\n       if(length(dir) = 0, '/', concat('/', arrayStringConcat(dir, '/'))) as dir,\n       COUNT(files.file_name)                                                file_count,\n       sum(files.lines)                                                      total_lines,\n       sum(files.insertions)                                                 total_insertions,\n       sum(files.deletions)                                                  total_deletions\nfrom (select search_key__owner,\n             search_key__repo,\n             author_email,\n             `files.insertions`,\n             `files.deletions`,\n             `files.lines`,\n             `files.file_name`,\n             splitByChar('/', `files.file_name`) as f_name,\n             length(f_name)                      as len,\n             arrayPopBack(f_name)                as dir\n      from gits g\n          array join\n          files.file_name\n         , files.insertions\n         , files.deletions\n         , files.lines\n      WHERE if_merged = 0\n        and search_key__owner = 'google'\n        and search_key__repo = 'leveldb'\n        and author_email = 'cmumford@google.com'\n        and (len = 2 or len = 1))\ngroup by search_key__owner, search_key__repo, author_email, dir",
     "round": "0s"
    }
   ]
  }
 ]
}